'use client';
import {useState} from 'react';
import type {DivisionalPnlReport} from '@/lib/seams/divisional-pnl';
import {useApi,useSession,Section,Field,field,Btn,Loading,ErrorState,money} from './kit';

function period(monthOffset=0){const now=new Date(),first=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+monthOffset,1));return {start:first.toISOString().slice(0,10),end:(monthOffset===0?now:new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0))).toISOString().slice(0,10)};}
export function DivisionalPnlPanel(){
 const session=useSession();
 return session.can('commercial.view')&&session.can('reports.view')&&session.module('reports')?<PnlReport/>:null;
}
function PnlReport(){
 const [dates,setDates]=useState(()=>period()),[division,setDivision]=useState(''),[applied,setApplied]=useState(()=>({...period(),division:''}));
 const q=new URLSearchParams({start:applied.start,end:applied.end,...(applied.division?{divisionId:applied.division}:{})});
 const {data,error,loading,refresh}=useApi<DivisionalPnlReport>(`/api/reports/divisional-pnl?${q}`);
 const [kind,setKind]=useState('all');
 const valid=dates.start&&dates.end&&dates.start<=dates.end;
 const apply=(next=dates)=>{setApplied({...next,division});refresh();};
 return <Section title="Divisional P&L — provisional" description="Billed revenue (ex GST) and recorded job costs (GST basis unknown). Profit, margin, accounting actuals, overheads and net result are unavailable.">
  <form className="grid items-end gap-3 sm:grid-cols-4" onSubmit={e=>{e.preventDefault();apply();}}>
   <Field label="From"><input className={field} type="date" required value={dates.start} onChange={e=>setDates({...dates,start:e.target.value})}/></Field>
   <Field label="To (inclusive)"><input className={field} type="date" required value={dates.end} onChange={e=>setDates({...dates,end:e.target.value})}/></Field>
   <Field label="Division"><select className={field} value={division} onChange={e=>setDivision(e.target.value)}><option value="">Company — authorized scope</option>{data?.availableDivisions.map(d=><option key={d.id} value={d.id}>{d.code} · {d.name}</option>)}{data?.scope==='All authorized divisions'&&<option value="unallocated">Unallocated</option>}</select></Field>
   <Btn type="submit" disabled={!valid||loading}>Generate report</Btn>
  </form>
  <div className="my-3 flex flex-wrap gap-2"><Btn variant="secondary" onClick={()=>{const p=period();setDates(p);apply(p);}}>This month</Btn><Btn variant="secondary" onClick={()=>{const p=period(-1);setDates(p);apply(p);}}>Last month</Btn><Btn variant="secondary" onClick={()=>{const now=new Date(),p={start:`${now.getUTCFullYear()}-01-01`,end:now.toISOString().slice(0,10)};setDates(p);apply(p);}}>Calendar YTD</Btn></div>
  <ErrorState error={error} onRetry={refresh}/>
  {loading?<Loading label="Generating divisional report…"/>:!error&&data&&<>
   <div className="my-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm"><strong>Provisional · Not reconciled</strong><p>{data.scope} · {data.period.start} to {data.period.end} · AUD · Generated {new Date(data.generatedAt).toLocaleString('en-AU')}</p><p>{data.profitability.reason}</p><p>Overheads and net result are unknown, not zero. Consolidation has no internal-charge eliminations.</p>{data.sources.some(s=>s.status==='not_posted')&&<p>Approved dockets missing cost postings: {data.sources.filter(s=>s.status==='not_posted').length}. See excluded source rows; these amounts are absent from the totals.</p>}</div>
   <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><caption className="sr-only">Provisional divisional profit and loss</caption><thead><tr>{['Division','Billed revenue (ex GST)','Recorded direct costs (GST basis unknown)','Gross profit (unavailable)','Overheads','Net result'].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{[...data.divisions,{id:'total',name:applied.division?'Selected total':'Consolidated authorized scope',code:'',...data.totals}].map(d=><tr key={d.id} className={d.id==='total'?'bg-slate-100 font-semibold':''}><th className="p-2">{d.code} {d.name}</th>{[d.revenue,d.directCosts,d.grossProfit,d.overheads,d.netResult].map((v,n)=><td className="p-2" key={n}>{v===null?'Not available':money(v,true)}</td>)}</tr>)}</tbody></table></div>
   <details className="mt-4 rounded-lg border p-3" open><summary className="cursor-pointer font-semibold">Definitions and source coverage</summary><dl className="mt-2 grid gap-2 text-sm">{Object.entries(data.definitions).map(([k,v])=><div key={k}><dt className="font-medium">{({revenue:'Revenue',directCosts:'Direct costs',grossProfit:'Gross profit',overheads:'Overheads',netResult:'Net result'} as Record<string,string>)[k]}</dt><dd className="text-slate-600">{v}</dd></div>)}</dl><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-slate-600">{data.warnings.map(w=><li key={w}>{w}</li>)}<li>{data.allocation.status}. Shared overhead remains unallocated; no amount has been invented.</li></ul></details>
   <details className="mt-3 rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Source drill-down ({data.sources.length} records; {data.sources.filter(s=>s.exclusion).length} excluded)</summary>
    <div className="my-3 max-w-xs"><Field label="Source type"><select className={field} value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All sources</option><option value="invoice">Client invoices</option><option value="cost">Cost transactions</option></select></Field></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr>{['Date','Division / project','Source reference / line','Category / code','Description','Amount / GST basis','Treatment'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody className="divide-y">{data.sources.filter(s=>kind==='all'||s.kind===kind).map((s,index)=><tr key={`${s.kind}:${s.id}:${index}`}><td className="p-2">{s.date}</td><td className="p-2">{data.divisions.find(d=>d.id===s.divisionId)?.name}<br/>{s.projectName}</td><td className="max-w-64 break-words p-2">{s.sourceType}: {s.reference}{s.sourceLine?` / ${s.sourceLine}`:''}<details><summary>Record IDs</summary><p>Record: {s.id}<br/>Project: {s.projectId}<br/>Source: {s.sourceId}</p></details></td><td className="p-2">{s.category} / {s.costCode??'Unmapped'}</td><td className="p-2">{s.description}</td><td className="p-2">{money(s.amount,true)}<br/><span className="text-xs text-slate-600">{s.taxBasis==='ex_gst'?'Ex GST':'GST basis unknown'}</span></td><td className="p-2">{s.exclusion??'Included — provisional'} ({s.status})</td></tr>)}</tbody></table>{!data.sources.length&&<p className="py-4 text-sm">No source records in this period. This does not establish zero business activity.</p>}</div>
   </details>
   {data.projects.length>0&&<details className="mt-3 rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Job-cost learning and estimate lineage</summary><p className="my-2 text-sm text-slate-600">Original whole-job baseline versus recorded docket costs through {data.period.end}. This is not a period budget variance or forecast final cost. Recorded costs have an unknown GST basis; no comparable budget variance is calculated. Jobs can be incomplete; baseline indirect costs and missing actual sources make the comparison incomplete.</p><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr>{['Project','Original budget','Costs through period end (GST basis unknown)','Costs in period (GST basis unknown)','Baseline / estimate IDs'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody className="divide-y">{data.projects.map(p=><tr key={p.id}><td className="p-2">{p.name}</td><td className="p-2">{p.baseline===null?'No baseline':money(p.baseline,true)}</td><td className="p-2">{money(p.costToDate,true)}</td><td className="p-2">{money(p.periodCosts,true)}</td><td className="max-w-64 break-words p-2">{p.baselineId??'None'} / {p.estimateId??'Not available'}</td></tr>)}</tbody></table></div></details>}
  </>}
 </Section>;
}
