'use client';
import {useState} from 'react';
import {Bell,Settings2} from 'lucide-react';
import {Sheet,SheetContent,SheetDescription,SheetTitle} from '@/components/ui/sheet';
import {api,useAction,useApi,Btn,ErrorState,Field,field,EmptyState} from './kit';
import {useNav} from './nav';

type NotificationFeed={unread:number;notifications:Array<{id:string;kind:string;title:string;body:string;readAt:string|null;createdAt:string;target:{area:string|null;sub:string|null;id:string|null;tab:string|null}}>;preferences:{inApp:boolean;email:boolean;sms:boolean;quietStart:string|null;quietEnd:string|null;timezone:string}};
const when=(v:string)=>new Date(v).toLocaleString('en-AU',{timeZone:'Australia/Sydney',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'});

export function NotificationCenter(){
 const {navigate}=useNav(),feed=useApi<NotificationFeed>('/api/communications/notifications?limit=50'),save=useAction();
 const [open,setOpen]=useState(false),[settings,setSettings]=useState(false);
 const pref=feed.data?.preferences;
 const [draft,setDraft]=useState<{email:boolean;sms:boolean;quietStart:string;quietEnd:string;timezone:string}|null>(null);
 const openTarget=async(n:NotificationFeed['notifications'][number])=>{await api('/api/communications/notifications',{method:'PATCH',body:{action:'read',id:n.id}}).catch(()=>{});feed.refresh();setOpen(false);if(n.target.area)navigate(n.target.area,n.target.sub||undefined,n.target.id||undefined,n.target.tab||undefined);};
 return <><button type="button" onClick={()=>{setOpen(true);feed.refresh();}} className="relative flex size-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-600 shadow-sm hover:border-slate-300" aria-label={'Notifications'+(feed.data?.unread?', '+feed.data.unread+' unread':'')}><Bell aria-hidden className="size-4.5"/>{Boolean(feed.data?.unread)&&<span className="absolute -right-1 -top-1 min-w-5 rounded-full bg-red-600 px-1 text-center text-[10px] font-bold leading-5 text-white">{Math.min(feed.data!.unread,99)}</span>}</button>
  <Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="w-[min(94vw,430px)] overflow-y-auto p-0"><SheetTitle className="sr-only">Notifications</SheetTitle><SheetDescription className="sr-only">Messages and work requiring your attention.</SheetDescription>
   <div className="flex items-center gap-2 border-b p-4"><Bell className="size-4"/><h2 className="font-semibold">Notifications</h2>{feed.data?.unread?<button type="button" className="ml-auto text-xs underline" onClick={()=>void api('/api/communications/notifications',{method:'PATCH',body:{action:'read',id:null}}).then(feed.refresh)}>Mark all read</button>:null}<button type="button" className="rounded p-1" onClick={()=>{setSettings(v=>!v);if(!draft&&pref)setDraft({email:pref.email,sms:pref.sms,quietStart:pref.quietStart||'',quietEnd:pref.quietEnd||'',timezone:pref.timezone});}} aria-label="Notification settings"><Settings2 className="size-4"/></button></div>
   {settings&&draft&&<div className="grid gap-3 border-b bg-slate-50 p-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={draft.email} onChange={e=>setDraft({...draft,email:e.target.checked})}/>Email notifications where configured</label><label className="flex items-center gap-2"><input type="checkbox" checked={draft.sms} onChange={e=>setDraft({...draft,sms:e.target.checked})}/>SMS preference <span className="text-xs text-slate-400">(provider required)</span></label><div className="grid grid-cols-2 gap-2"><Field label="Quiet from"><input className={field} type="time" value={draft.quietStart} onChange={e=>setDraft({...draft,quietStart:e.target.value})}/></Field><Field label="Quiet until"><input className={field} type="time" value={draft.quietEnd} onChange={e=>setDraft({...draft,quietEnd:e.target.value})}/></Field></div><Btn busy={save.busy} onClick={()=>void save.run(()=>api('/api/communications/notifications',{method:'PATCH',body:{action:'preferences',email:draft.email,sms:draft.sms,quietStart:draft.quietStart||null,quietEnd:draft.quietEnd||null,timezone:draft.timezone}}),feed.refresh)}>Save preferences</Btn></div>}
   <ErrorState error={feed.error||save.error} onRetry={feed.refresh}/>{!feed.data?.notifications.length?<div className="p-5"><EmptyState title="No notifications yet."/></div>:<ul className="divide-y">{feed.data.notifications.map(n=><li key={n.id}><button type="button" onClick={()=>void openTarget(n)} className={'w-full px-4 py-3 text-left hover:bg-slate-50 '+(n.readAt?'bg-white':'bg-sky-50/60')}><div className="flex items-start gap-2"><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{n.title}</span><span className="mt-0.5 block line-clamp-2 text-xs text-slate-600">{n.body}</span><span className="mt-1 block text-[10px] text-slate-400">{when(n.createdAt)}</span></span>{!n.readAt&&<span className="mt-1 size-2 rounded-full bg-sky-600"/>}</div></button></li>)}</ul>}
  </SheetContent></Sheet></>;
}
