'use client';
import {useState} from 'react';
import {api,useApi,useAction,useSession,PageHeader,Section,ErrorState,Btn,Pill} from './kit';
import {addDays,type Activity} from '@/lib/v1/program';
type Row=Activity&{revision:number;start:string;finish:string;delayDays:number;responsible:string;work_package:string;resource_requirement:string;planned_quantity:number;quantity_unit:string;production_per_day:number};
const field='w-full rounded border p-2 text-sm';
const empty=()=>({name:'',startDate:new Date().toLocaleDateString('en-CA',{timeZone:'Australia/Sydney'}),durationDays:1,predecessorId:null as string|null,responsible:'',workPackage:'',resourceRequirement:'',plannedQuantity:0,quantityUnit:'',productionPerDay:0,status:'planned'});
export function Program(){
 const [projectId,setProjectId]=useState(''),[view,setView]=useState('Programme'),[form,setForm]=useState(empty),[editing,setEditing]=useState<Row|null>(null);
 const data=useApi<{projects:{id:string;name:string}[];activities:Row[]}>(`/api/projects/program${projectId?'?projectId='+encodeURIComponent(projectId):''}`),action=useAction(),session=useSession();
 const writable=session.writable('projects')&&session.can('project.edit');
 const today=empty().startDate,end=addDays(today,13),rows=(data.data?.activities||[]).filter(a=>view!=='Two-week lookahead'||(a.finish>=today&&a.start<=end&&a.status!=='complete'));
 const patch=(key:string,value:unknown)=>setForm(f=>({...f,[key]:value}));
 return <div className="space-y-5"><PageHeader title="Planning & programme" subtitle="Calendar-day activities with finish-to-start dependencies. Projected dates update without changing your planned dates."/><ErrorState error={data.error||action.error}/>
 <label>Project<select className={field} value={projectId} onChange={e=>{setProjectId(e.target.value);setEditing(null);setForm(empty());}}><option value="">Choose project</option>{data.data?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 {projectId&&<><div className="flex gap-2">{['Programme','Two-week lookahead','Timeline'].map(v=><Btn key={v} variant="secondary" onClick={()=>setView(v)}>{v}</Btn>)}</div>
 <Section title={view}><div className="space-y-3">{rows.map(a=><article key={a.id} className="rounded border p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{a.name}</strong><Pill tone={a.delayDays?'warning':'neutral'}>{a.status.replaceAll('_',' ')}{a.delayDays?` · ${a.delayDays} days dependency delay`:''}</Pill></div><p className="text-sm">{a.start} → {a.finish} · {a.duration_days} calendar days · {a.responsible||'Unassigned'}</p><p className="text-sm text-slate-600">{a.work_package} · {a.resource_requirement}</p>{view==='Timeline'&&<div className="mt-2 flex overflow-hidden rounded bg-slate-100" aria-label={`${a.name}: ${a.start} to ${a.finish}`}>{Array.from({length:14},(_,i)=>addDays(today,i)).map(d=><span key={d} title={d} className={`flex-1 border-r py-2 text-center text-xs ${d>=a.start&&d<=a.finish?'bg-orange-200':'bg-slate-50'}`}>{d.slice(8)}</span>)}</div>}{writable&&<Btn variant="ghost" onClick={()=>{setEditing(a);setForm({name:a.name,startDate:a.start_date,durationDays:Number(a.duration_days),predecessorId:a.predecessor_id,responsible:a.responsible||'',workPackage:a.work_package||'',resourceRequirement:a.resource_requirement||'',plannedQuantity:Number(a.planned_quantity),quantityUnit:a.quantity_unit||'',productionPerDay:Number(a.production_per_day),status:a.status});}}>Edit activity</Btn>}</article>)}{!rows.length&&<p>No activities in this view.</p>}</div></Section>
 {writable&&<Section title={editing?'Edit activity':'Add activity'}><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void action.run(()=>api('/api/projects/program',{method:'POST',body:{...form,projectId,id:editing?.id,revision:editing?.revision}}),()=>{data.refresh();setEditing(null);setForm(empty());});}}>
 {([['name','Activity','text'],['startDate','Planned start','date'],['durationDays','Duration (calendar days)','number'],['responsible','Responsible person','text'],['workPackage','Work package','text'],['resourceRequirement','Crew / plant / subcontractor requirements','text'],['plannedQuantity','Planned quantity','number'],['quantityUnit','Quantity unit','text'],['productionPerDay','Production per day','number']] as const).map(([key,label,type])=><label key={key}>{label}<input className={field} required={['name','startDate','durationDays'].includes(key)} type={type} min={key==='durationDays'?1:0} step={type==='number'?'any':undefined} value={form[key]} onChange={e=>patch(key,type==='number'?Number(e.target.value):e.target.value)}/></label>)}
 <label>Predecessor<select className={field} value={form.predecessorId||''} onChange={e=>patch('predecessorId',e.target.value||null)}><option value="">None</option>{data.data?.activities.filter(a=>a.id!==editing?.id).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Status<select className={field} value={form.status} onChange={e=>patch('status',e.target.value)}>{['planned','in_progress','complete','on_hold'].map(s=><option key={s}>{s}</option>)}</select></label>
 {form.productionPerDay>0&&<p>Production assumption: {Math.ceil(form.plannedQuantity/form.productionPerDay)} working days. Confirm calendar allowance in Duration.</p>}<button className={field} disabled={action.busy}>Save activity</button>{editing&&<Btn variant="secondary" onClick={()=>{setEditing(null);setForm(empty());}}>Cancel edit</Btn>}</form></Section>}</>}
 </div>;
}
