'use client';
import {useApi,ErrorState,Loading,PageHeader,Section,Stat,money,pct,EmptyState,Btn,StatusBadge} from './kit';
import {stateLabel} from '@/lib/platform/workflow';

type R={generatedAt:string;commercialVisible:boolean;
 pipeline?:{opportunities:Array<{stage:string;count:number;value?:number;weighted?:number}>;tenders:Array<{stage:string;count:number;value?:number}>;conversionPct:number|null;decided:number};
 projects?:{byStage:Record<string,number>;active:number;total:number};
 commercial?:{projects:Array<Record<string,unknown>>;totals:Record<string,number|null>;variations:Array<{status:string;count:number;value:number}>;claims:Array<{status:string;count:number;value:number}>};
 learn?:Array<{id:string;name:string;estimatedCost:number|null;actualCost:number;forecastFinalCost:number;tenderMarginPct:number|null;forecastMarginPct:number|null;estimatedLabourHours:number|null;actualLabourHours:number|null}>;
 operations?:{upcomingShifts14d:number;completedShifts30d:number;plannedHoursByCategory:Record<string,number>;fieldRecords30d:number;tonnesRecorded30d:number};
 dockets?:Record<string,{count:number;value?:number}>;
 hseq?:{openActions:number;overdueActions:number;incidents:Array<{type:string;status:string;count:number}>;ncrs:Record<string,number>;swms:Record<string,number>;itpItems:Record<string,number>}};

export function ReportsV1(){
 const {data,error,loading,refresh}=useApi<R>('/api/reports/v1');
 return <div className="grid gap-4">
  <PageHeader title="Reports" subtitle={data?`Derived from your records · generated ${new Date(data.generatedAt).toLocaleString('en-AU')}`:'Derived from your records'} actions={<Btn variant="secondary" onClick={refresh}>Refresh</Btn>}/>
  <ErrorState error={error} onRetry={refresh}/>
  {loading&&!data?<Loading/>:data&&<>
   {data.pipeline&&<Section title="Pipeline"><div className="grid gap-3 sm:grid-cols-3"><Stat label="Tender conversion" value={pct(data.pipeline.conversionPct)} hint={`${data.pipeline.decided} tender(s) decided`}/>{data.pipeline.tenders.map(t=><Stat key={t.stage} label={`Tenders · ${stateLabel('tender',t.stage)}`} value={t.count} hint={t.value!=null?money(t.value):undefined}/>)}</div>
    {data.pipeline.opportunities.length?<table className="mt-4 w-full text-sm"><thead className="text-left text-xs text-slate-500"><tr><th className="py-1">Opportunity stage</th><th>Count</th>{data.commercialVisible&&<><th>Value</th><th>Weighted</th></>}</tr></thead><tbody className="divide-y">{data.pipeline.opportunities.map(o=><tr key={o.stage}><td className="py-1.5">{stateLabel('opportunity',o.stage)}</td><td>{o.count}</td>{data.commercialVisible&&<><td>{money(o.value)}</td><td>{money(o.weighted)}</td></>}</tr>)}</tbody></table>:<EmptyState title="No opportunities recorded."/>}</Section>}
   {data.projects&&<Section title="Projects"><div className="grid gap-3 sm:grid-cols-4"><Stat label="Active" value={data.projects.active}/><Stat label="Total" value={data.projects.total}/>{Object.entries(data.projects.byStage).map(([k,v])=><Stat key={k} label={stateLabel('project',k)} value={v}/>)}</div></Section>}
   {data.commercial&&<Section title="Commercial (ex GST)"><div className="grid gap-3 sm:grid-cols-4">{([['currentContract','Current contract value'],['approvedVariations','Approved variations'],['pendingVariations','Pending variations'],['actual','Actual cost'],['forecastFinalCost','Forecast final cost'],['forecastProfit','Forecast profit'],['claimed','Claimed'],['certified','Certified'],['invoiced','Invoiced'],['paid','Paid'],['unbilled','Unbilled work']] as const).map(([k,l])=><Stat key={k} label={l} value={money(data.commercial!.totals[k])}/>)}<Stat label="Forecast margin" value={pct(data.commercial.totals.forecastMarginPct)}/></div>
    <div className="mt-4 grid gap-4 sm:grid-cols-2"><div><p className="text-sm font-semibold">Variations</p>{data.commercial.variations.length?<ul className="text-sm">{data.commercial.variations.map(v=><li key={v.status} className="flex justify-between py-1"><StatusBadge machine="variation" state={v.status}/><span>{v.count} · {money(v.value)}</span></li>)}</ul>:<p className="text-sm text-slate-500">None recorded.</p>}</div><div><p className="text-sm font-semibold">Claims</p>{data.commercial.claims.length?<ul className="text-sm">{data.commercial.claims.map(v=><li key={v.status} className="flex justify-between py-1"><StatusBadge machine="claim" state={v.status}/><span>{v.count} · {money(v.value)}</span></li>)}</ul>:<p className="text-sm text-slate-500">None recorded.</p>}</div></div></Section>}
   {data.learn&&<Section title="Learn: estimate vs actual" description="Deterministic comparison for projects with an estimate baseline. No predictions.">{data.learn.length?<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="text-left text-xs text-slate-500"><tr><th className="py-1">Project</th><th>Estimated cost</th><th>Actual to date</th><th>Forecast final</th><th>Tender margin</th><th>Forecast margin</th><th>Labour hrs est / act</th></tr></thead><tbody className="divide-y">{data.learn.map(l=><tr key={l.id}><td className="py-1.5">{l.name}</td><td>{money(l.estimatedCost)}</td><td>{money(l.actualCost)}</td><td>{money(l.forecastFinalCost)}</td><td>{pct(l.tenderMarginPct)}</td><td>{pct(l.forecastMarginPct)}</td><td>{l.estimatedLabourHours??'N/A'} / {l.actualLabourHours??'N/A'}</td></tr>)}</tbody></table></div>:<EmptyState title="No projects with an estimate baseline yet."/>}</Section>}
   {data.operations&&<Section title="Operations"><div className="grid gap-3 sm:grid-cols-4"><Stat label="Shifts next 14 days" value={data.operations.upcomingShifts14d}/><Stat label="Shifts completed (30 days)" value={data.operations.completedShifts30d}/><Stat label="Field records (30 days)" value={data.operations.fieldRecords30d}/><Stat label="Tonnes recorded (30 days)" value={data.operations.tonnesRecorded30d}/>{Object.entries(data.operations.plannedHoursByCategory).map(([k,v])=><Stat key={k} label={`Planned ${k} hours`} value={v}/>)}</div></Section>}
   {data.dockets&&<Section title="Dockets"><div className="grid gap-3 sm:grid-cols-4">{([['pendingReview','Pending review'],['approvedUnclaimed','Approved, unclaimed'],['claimed','Claimed'],['rejected','Rejected']] as const).map(([k,l])=><Stat key={k} label={l} value={data.dockets![k].count} hint={data.dockets![k].value!=null?money(data.dockets![k].value):undefined}/>)}</div></Section>}
   {data.hseq&&<Section title="HSEQ"><div className="grid gap-3 sm:grid-cols-4"><Stat label="Open corrective actions" value={data.hseq.openActions} tone={data.hseq.overdueActions?'warn':undefined} hint={`${data.hseq.overdueActions} overdue`}/><Stat label="Open NCRs" value={Object.entries(data.hseq.ncrs).filter(([k])=>k!=='closed').reduce((n,[,v])=>n+v,0)}/><Stat label="Incidents recorded" value={data.hseq.incidents.reduce((n,i)=>n+i.count,0)}/><Stat label="SWMS issued" value={data.hseq.swms.issued||0} hint={`${data.hseq.swms.review||0} in review`}/><Stat label="ITP points open" value={data.hseq.itpItems.open||0} hint={`${data.hseq.itpItems.pass||0} passed · ${data.hseq.itpItems.fail||0} failed`}/></div></Section>}
  </>}
 </div>;
}
