'use client';
import {useState} from 'react';
import {api,useApi,useAction,useSession,PageHeader,Section,ErrorState,Loading,Btn,Pill} from './kit';
type Asset={id:string;name:string;status:string;plant_number:string;meter_type:string|null;current_meter:number|null;next_service_meter:number|null};
type Order={id:string;asset_id:string;title:string;severity:string;status:string;revision:number;source_type?:string|null};
type Entry={id:string;order_id:string;kind:string;note:string;parts:string|null;labour_hours:string|null;created_at:string};
const inputClass='w-full rounded-lg border bg-white p-2 text-sm';
export function Workshop(){
 const session=useSession(),data=useApi<{assets:Asset[];orders:Order[];entries:Entry[];readings:{id:string;asset_id:string;reading:number;meter_type:string;note:string;created_at:string}[]}>('/api/workshop'),action=useAction();
 const [assetId,setAssetId]=useState(''),[title,setTitle]=useState(''),[note,setNote]=useState(''),[severity,setSeverity]=useState('minor');
 const [newAsset,setNewAsset]=useState(false),[name,setName]=useState(''),[number,setNumber]=useState(''),[category,setCategory]=useState(''),[registration,setRegistration]=useState('');
 const [meter,setMeter]=useState(''),[nextService,setNextService]=useState(''),[meterType,setMeterType]=useState('hours'),[meterNote,setMeterNote]=useState('');
 const [selected,setSelected]=useState(''),[repairNote,setRepairNote]=useState(''),[parts,setParts]=useState(''),[hours,setHours]=useState('0');
 const editable=session.writable('workshop')&&session.can('workshop.edit'),verify=session.writable('workshop')&&session.can('workshop.verify');
 const order=data.data?.orders.find(o=>o.id===selected);
 const save=(body:unknown)=>action.run(()=>api('/api/workshop',{method:'POST',body}),()=>{data.refresh();setNote('');setTitle('');setRepairNote('');setParts('');});
 if(data.loading&&!data.data)return <Loading/>;
 return <div className="space-y-5"><PageHeader title="Workshop & fleet" subtitle="Report defects, record repairs and independently verify return to service."/><ErrorState error={data.error||action.error}/>
 {!session.writable('workshop')&&<p role="status">Read-only: existing assets and maintenance history remain available.</p>}
 <Section title="Assets" actions={editable&&<Btn onClick={()=>setNewAsset(!newAsset)}>Add asset</Btn>}>
 {newAsset&&<form className="mb-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void action.run(()=>api('/api/workshop',{method:'POST',body:{action:'asset',name,number,category,registration}}),()=>{setNewAsset(false);setName('');data.refresh();});}}>
 <label>Asset name<input required className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></label><label>Asset number<input className={inputClass} value={number} onChange={e=>setNumber(e.target.value)}/></label><label>Category<input className={inputClass} value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Registration<input className={inputClass} value={registration} onChange={e=>setRegistration(e.target.value)}/></label><button disabled={action.busy} className={inputClass}>Save asset</button></form>}
 <div className="grid gap-3 sm:grid-cols-3">{data.data?.assets.map(a=><button key={a.id} onClick={()=>setAssetId(a.id)} className={`rounded-lg border p-3 text-left ${assetId===a.id?'border-orange-500 bg-orange-50':''}`}><strong>{a.name}</strong><p className="text-xs">{a.plant_number}</p>{a.current_meter!=null&&<p className="text-xs">{a.current_meter} {a.meter_type} · service at {a.next_service_meter}</p>}{a.current_meter!=null&&a.next_service_meter!=null&&Number(a.current_meter)>=Number(a.next_service_meter)&&<Pill tone="warning">Service due</Pill>}<Pill tone={a.status==='Out of service'?'danger':'neutral'}>{a.status}</Pill></button>)}</div>{!data.data?.assets.length&&<p>Add your first asset to start recording defects and repairs.</p>}
 </Section>
 {assetId&&<Section title="Meter & servicing"><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save({action:'meter',assetId,meterType,reading:Number(meter),nextService:Number(nextService),note:meterNote});}}>{editable&&<><label>Meter units<select className={inputClass} value={meterType} onChange={e=>setMeterType(e.target.value)}><option value="hours">Hours</option><option value="km">Kilometres</option></select></label><label>Current reading<input required type="number" min="0" step="0.01" className={inputClass} value={meter} onChange={e=>setMeter(e.target.value)}/></label><label>Next service at<input required type="number" min="0" step="0.01" className={inputClass} value={nextService} onChange={e=>setNextService(e.target.value)}/></label><label>Reading / service schedule evidence<textarea required className={inputClass} value={meterNote} onChange={e=>setMeterNote(e.target.value)}/></label><button disabled={action.busy} className={inputClass}>Record meter & service threshold</button></>}</form><ol className="mt-3 space-y-2">{data.data?.readings.filter(r=>r.asset_id===assetId).map(r=><li key={r.id} className="text-sm">{r.reading} {r.meter_type} · {new Date(r.created_at).toLocaleString()} · {r.note}</li>)}</ol></Section>}
 {editable&&<Section title="Report defect" description="Critical defects immediately take the asset out of service. They remain blocked until independently verified."><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save({action:'defect',assetId,title,note,severity});}}>
 <label>Asset<select required className={inputClass} value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">Choose asset</option>{data.data?.assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Severity<select className={inputClass} value={severity} onChange={e=>setSeverity(e.target.value)}>{['minor','major','critical'].map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Defect<input required maxLength={180} className={inputClass} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Inspection evidence / description<textarea required className={inputClass} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={action.busy} className={inputClass}>Create work order</button></form></Section>}
 <Section title="Work orders"><div className="space-y-2">{data.data?.orders.map(o=><button key={o.id} onClick={()=>{setSelected(o.id);setRepairNote('');}} className="flex w-full flex-wrap justify-between gap-2 rounded-lg border p-3 text-left"><span>{o.title}<small className="block">{data.data?.assets.find(a=>a.id===o.asset_id)?.name} · {o.severity}{o.source_type==='form_submission'?' · raised from a form':''}</small></span><Pill>{o.status.replaceAll('_',' ')}</Pill></button>)}{!data.data?.orders.length&&<p>No defects recorded.</p>}</div></Section>
 {order&&<Section title={order.title} description="History is append-only. Repairs must be verified by a different authorised person."><ol className="mb-4 space-y-3">{data.data?.entries.filter(e=>e.order_id===order.id).map(e=><li key={e.id} className="rounded border p-3"><strong>{e.kind}</strong><small className="ml-2">{new Date(e.created_at).toLocaleString()}</small><p className="whitespace-pre-wrap">{e.note}</p>{e.parts&&<p>Parts: {e.parts}</p>}{e.labour_hours!=null&&<p>Labour: {e.labour_hours} hours</p>}</li>)}</ol>
 {order.status!=='closed'&&<div className="space-y-3"><label>Repair / verification notes<textarea className={inputClass} value={repairNote} onChange={e=>setRepairNote(e.target.value)}/></label>
 {editable&&['open','rework'].includes(order.status)&&<><label>Labour hours<input type="number" min="0" step="0.25" className={inputClass} value={hours} onChange={e=>setHours(e.target.value)}/></label><label>Parts / external repair<textarea className={inputClass} value={parts} onChange={e=>setParts(e.target.value)}/></label><Btn disabled={action.busy||!repairNote.trim()} onClick={()=>void save({action:'repair',id:order.id,revision:order.revision,note:repairNote,labourHours:Number(hours),parts})}>Complete repair for verification</Btn></>}
 {verify&&order.status==='awaiting_verification'&&<div className="flex gap-3">{[true,false].map(accepted=><Btn key={String(accepted)} disabled={action.busy||!repairNote.trim()} onClick={()=>void save({action:'verify',id:order.id,revision:order.revision,note:repairNote,accepted})}>{accepted?'Verify repair':'Return for rework'}</Btn>)}</div>}</div>}
 </Section>}</div>;
}
