'use client';
import {useState} from 'react';
import {api,useApi,useAction,useSession,PageHeader,Section,ErrorState,Loading,Btn,Pill} from './kit';
import {FormLauncher,SubmissionList,SubmissionSheet} from './forms';
type ServiceState={overdue:boolean;meterReached:boolean;datePassed:boolean};
type Asset={id:string;name:string;status:string;plant_number:string;revision:number;meter_type:string|null;current_meter:number|null;next_service_meter:number|null;next_service_date:string|null;service:ServiceState};
type ServiceEvent={id:string;asset_id:string;kind:string;actor_name:string|null;performed_on:string|null;recorded_at:string;meter_type:string|null;meter_reading:string|null;previous_next_service_meter:string|null;previous_next_service_date:string|null;new_next_service_meter:string|null;new_next_service_date:string|null;note:string|null;reason:string|null};
const EVENT_LABEL:Record<string,string>={completed:'Service completed',plan_set:'Plan set',plan_corrected:'Plan corrected'};
type Order={id:string;asset_id:string;title:string;severity:string;status:string;revision:number;source_type?:string|null;source_field?:string|null};
type Source={restricted:boolean;submissionId:string;formName:string;versionNumber:number;submittedAt:string;submittedByName:string|null;contextType:string;contextLabel:string;projectName:string|null;shiftId:string|null;fieldLabel:string;amendmentSequence:number|null;currentAmendmentSequence:number;evidenceState:string};
const SOURCE_KIND:Record<string,string>={shift:'Shift',project:'Project',asset:'Plant',organisation:'Company'};
/** Traceability for a form-raised order. Content comes from the Forms API, which re-checks the viewer's scope; nothing is copied into Workshop. */
function OrderSource({orderId}:{orderId:string}){
 const session=useSession(),[view,setView]=useState<string|null>(null);
 const {data,error}=useApi<{source:Source|{restricted:true}|null}>(session.module('ims')&&session.can('forms.view')?`/api/forms/defects?workOrderId=${encodeURIComponent(orderId)}`:null);
 const src=data?.source;
 if(!session.module('ims')||!session.can('forms.view'))return <p className="mb-3 text-sm text-slate-600">Raised from a form. The source is not available to you.</p>;
 if(error)return <p className="mb-3 text-sm text-slate-600">Raised from a form. The source is not available to you.</p>;
 if(!src)return null;
 if(src.restricted)return <p className="mb-3 text-sm text-slate-600">Raised from a form you are not authorised to view.</p>;
 const s=src as Source;
 return <div className="mb-4 grid gap-1 rounded-lg border bg-slate-50 p-3 text-sm"><p className="font-medium">Raised from form: {s.formName} <span className="text-xs font-normal text-slate-500">v{s.versionNumber}</span></p>
  <p>Submitted {new Date(s.submittedAt).toLocaleString()}{s.submittedByName?` by ${s.submittedByName}`:''}</p>
  <p>{SOURCE_KIND[s.contextType]||'Context'}: {s.contextLabel}{s.projectName&&s.contextType!=='project'?` · Project: ${s.projectName}`:''}</p>
  <p>Answer: {s.fieldLabel}</p>
  <p>Evidence state when raised: <strong>{s.evidenceState}</strong>{s.amendmentSequence!=null&&s.currentAmendmentSequence>s.amendmentSequence?` (the form has since been corrected to correction ${s.currentAmendmentSequence})`:''}</p>
  <Btn variant="secondary" className="mt-1 justify-self-start" onClick={()=>setView(s.submissionId)}>View source inspection</Btn>
  <SubmissionSheet id={view} onClose={()=>setView(null)}/></div>;
}

const planText=(meter:unknown,date:unknown,unit:string|null)=>[meter!=null&&meter!==''?`${Number(meter)} ${unit||''}`.trim():null,date||null].filter(Boolean).join(' · ')||'none';
/** Service plan for one asset. A meter reading never changes the plan; a completed service and an administrator plan correction are separate, audited actions. */
function ServicePanel({asset,readings,events,today,editable,canCorrect,refresh}:{asset:Asset;readings:{id:string;asset_id:string;reading:number;meter_type:string;note:string;created_at:string}[];events:ServiceEvent[];today:string;editable:boolean;canCorrect:boolean;refresh:()=>void}){
 const action=useAction(),[meterType,setMeterType]=useState(asset.meter_type||'hours'),[reading,setReading]=useState(''),[evidence,setEvidence]=useState('');
 const [planMeter,setPlanMeter]=useState(''),[planDate,setPlanDate]=useState(''),[planNote,setPlanNote]=useState('');
 const [performedOn,setPerformedOn]=useState(today),[svcMeter,setSvcMeter]=useState(''),[svcNextMeter,setSvcNextMeter]=useState(''),[svcNextDate,setSvcNextDate]=useState(''),[svcNote,setSvcNote]=useState(''),[requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const [fixMeter,setFixMeter]=useState(asset.next_service_meter==null?'':String(Number(asset.next_service_meter))),[fixDate,setFixDate]=useState(asset.next_service_date||''),[fixReason,setFixReason]=useState('');
 const hasPlan=asset.next_service_meter!=null||Boolean(asset.next_service_date),history=events.filter(e=>e.asset_id===asset.id);
 const send=(body:Record<string,unknown>,done:()=>void)=>void action.run(()=>api('/api/workshop',{method:'POST',body}),()=>{done();refresh();});
 return <Section title="Meter & servicing" description="A meter reading never changes the service plan. Record a completed service, or ask an administrator to correct the plan.">
  <ErrorState error={action.error}/>
  <p className="mb-2 text-sm"><strong>Service plan:</strong> {planText(asset.next_service_meter,asset.next_service_date,asset.meter_type)}{asset.current_meter!=null&&<span> · latest reading {Number(asset.current_meter)} {asset.meter_type}</span>} {asset.service.overdue&&<Pill tone="warning">Service overdue</Pill>}</p>
  {asset.service.overdue&&<p role="status" className="mb-3 rounded bg-amber-50 p-2 text-sm text-amber-900">{asset.service.datePassed?`The service date has passed (today ${today}). `:''}{asset.service.meterReached?'The service meter has been reached. ':''}Scheduling shows a warning. Only a recorded service or an administrator plan correction changes this.</p>}
  {editable&&<form aria-label="Record meter reading" className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();send({action:'meter',assetId:asset.id,meterType,reading:Number(reading),note:evidence},()=>{setReading('');setEvidence('');});}}>
   <label>Meter units<select className={inputClass} value={meterType} disabled={Boolean(asset.meter_type)} onChange={e=>setMeterType(e.target.value)}><option value="hours">Hours</option><option value="km">Kilometres</option></select></label>
   <label>Current reading<input required type="number" min="0" step="0.01" className={inputClass} value={reading} onChange={e=>setReading(e.target.value)}/></label>
   <label className="sm:col-span-2">Reading evidence<textarea required className={inputClass} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><button disabled={action.busy} className={inputClass}>Record meter reading</button></form>}
  {editable&&!hasPlan&&<form aria-label="Set initial service plan" className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();send({action:'plan',assetId:asset.id,revision:asset.revision,...(planMeter?{nextServiceMeter:Number(planMeter)}:{}),...(planDate?{nextServiceDate:planDate}:{}),note:planNote},()=>{setPlanMeter('');setPlanDate('');setPlanNote('');});}}>
   <h4 className="font-semibold sm:col-span-2">Set initial service plan</h4><p className="text-sm text-slate-600 sm:col-span-2">No service plan is recorded for this asset. Nothing is assumed.</p>
   {asset.meter_type&&<label>Next service at ({asset.meter_type})<input type="number" min="0" step="0.01" className={inputClass} value={planMeter} onChange={e=>setPlanMeter(e.target.value)}/></label>}<label>Next service date<input type="date" className={inputClass} value={planDate} onChange={e=>setPlanDate(e.target.value)}/></label>
   <label className="sm:col-span-2">Basis for the plan<textarea required className={inputClass} value={planNote} onChange={e=>setPlanNote(e.target.value)}/></label><button disabled={action.busy||(!planMeter&&!planDate)} className={inputClass}>Set service plan</button></form>}
  {editable&&hasPlan&&<form aria-label="Record completed service" className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();send({action:'service',assetId:asset.id,revision:asset.revision,performedOn,...(svcMeter?{meterReading:Number(svcMeter)}:{}),...(!asset.meter_type&&svcMeter?{meterType}:{}),...(svcNextMeter?{nextServiceMeter:Number(svcNextMeter)}:{}),...(svcNextDate?{nextServiceDate:svcNextDate}:{}),note:svcNote,clientRequestId:requestId},()=>{setSvcMeter('');setSvcNextMeter('');setSvcNextDate('');setSvcNote('');setRequestId(crypto.randomUUID());});}}>
   <h4 className="font-semibold sm:col-span-2">Record completed service</h4><p className="text-sm text-slate-600 sm:col-span-2">Records who, when, the meter reading and the next thresholds. Recording a service never returns an asset from a critical-defect safety hold.</p>
   <label>Date performed<input required type="date" max={today} className={inputClass} value={performedOn} onChange={e=>setPerformedOn(e.target.value)}/></label>
   {(asset.meter_type||asset.next_service_meter!=null)&&<label>Meter reading at service<input required type="number" min="0" step="0.01" className={inputClass} value={svcMeter} onChange={e=>setSvcMeter(e.target.value)}/></label>}
   {asset.next_service_meter!=null&&<label>Next service at ({asset.meter_type})<input required type="number" min="0" step="0.01" className={inputClass} value={svcNextMeter} onChange={e=>setSvcNextMeter(e.target.value)}/></label>}{asset.next_service_date&&<label>Next service date<input required type="date" className={inputClass} value={svcNextDate} onChange={e=>setSvcNextDate(e.target.value)}/></label>}
   <label className="sm:col-span-2">Work performed<textarea required className={inputClass} value={svcNote} onChange={e=>setSvcNote(e.target.value)}/></label><button disabled={action.busy} className={inputClass}>Record completed service</button></form>}
  {canCorrect&&hasPlan&&<form aria-label="Correct service plan" className="mt-4 grid gap-3 rounded-lg border border-amber-300 p-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();send({action:'correct',assetId:asset.id,revision:asset.revision,nextServiceMeter:fixMeter?Number(fixMeter):null,nextServiceDate:fixDate||null,reason:fixReason},()=>setFixReason(''));}}>
   <h4 className="font-semibold sm:col-span-2">Correct service plan (administrator)</h4><p className="text-sm text-slate-600 sm:col-span-2">Fixes a wrong plan entry. This is not a completed service and is recorded as “Plan corrected”.</p>
   {asset.meter_type&&<label>Next service at ({asset.meter_type})<input type="number" min="0" step="0.01" className={inputClass} value={fixMeter} onChange={e=>setFixMeter(e.target.value)}/></label>}<label>Next service date<input type="date" className={inputClass} value={fixDate} onChange={e=>setFixDate(e.target.value)}/></label>
   <label className="sm:col-span-2">Reason for correction (required)<textarea required minLength={10} className={inputClass} value={fixReason} onChange={e=>setFixReason(e.target.value)}/></label><button disabled={action.busy||fixReason.trim().length<10} className={inputClass}>Correct plan</button></form>}
  <h4 className="mt-4 font-semibold">Service history</h4>
  <ol className="mt-2 space-y-2">{history.map(e=><li key={e.id} className="rounded border p-2 text-sm"><strong>{EVENT_LABEL[e.kind]||e.kind}</strong>{e.performed_on?` · performed ${e.performed_on}`:''} · recorded {new Date(e.recorded_at).toLocaleString()}{e.actor_name?` · ${e.actor_name}`:''}
   {e.meter_reading!=null&&<span> · meter {Number(e.meter_reading)} {e.meter_type}</span>}<span> · plan {planText(e.previous_next_service_meter,e.previous_next_service_date,e.meter_type)} → {planText(e.new_next_service_meter,e.new_next_service_date,e.meter_type)}</span>{e.reason&&<span> · reason: {e.reason}</span>}{e.note&&<span> · {e.note}</span>}</li>)}{!history.length&&<li className="text-sm text-slate-500">No service or plan history recorded.</li>}</ol>
  <ol className="mt-3 space-y-1">{readings.filter(r=>r.asset_id===asset.id).map(r=><li key={r.id} className="text-sm text-slate-700">{r.reading} {r.meter_type} · {new Date(r.created_at).toLocaleString()} · {r.note}</li>)}</ol>
 </Section>;
}
type Entry={id:string;order_id:string;kind:string;note:string;parts:string|null;labour_hours:string|null;created_at:string};
const inputClass='w-full rounded-lg border bg-white p-2 text-sm';
export function Workshop(){
 const session=useSession(),data=useApi<{today:string;canCorrect:boolean;services:ServiceEvent[];assets:Asset[];orders:Order[];entries:Entry[];readings:{id:string;asset_id:string;reading:number;meter_type:string;note:string;created_at:string}[]}>('/api/workshop'),action=useAction();
 const [assetId,setAssetId]=useState(''),[title,setTitle]=useState(''),[note,setNote]=useState(''),[severity,setSeverity]=useState('minor');
 const [newAsset,setNewAsset]=useState(false),[name,setName]=useState(''),[number,setNumber]=useState(''),[category,setCategory]=useState(''),[registration,setRegistration]=useState('');
 const [selected,setSelected]=useState(''),[repairNote,setRepairNote]=useState(''),[parts,setParts]=useState(''),[hours,setHours]=useState('0');
 const editable=session.writable('workshop')&&session.can('workshop.edit'),verify=session.writable('workshop')&&session.can('workshop.verify');
 const order=data.data?.orders.find(o=>o.id===selected);
 const save=(body:unknown)=>action.run(()=>api('/api/workshop',{method:'POST',body}),()=>{data.refresh();setNote('');setTitle('');setRepairNote('');setParts('');});
 if(data.loading&&!data.data)return <Loading/>;
 return <div className="space-y-5"><PageHeader title="Workshop & fleet" subtitle="Report defects, record repairs and independently verify return to service."/><ErrorState error={data.error||action.error}/>
 {!session.writable('workshop')&&<p role="status">Read-only: existing assets and maintenance history remain available.</p>}
 <Section title="Assets" actions={editable&&<Btn onClick={()=>setNewAsset(!newAsset)}>Add asset</Btn>}>
 {newAsset&&<form className="mb-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void action.run(()=>api('/api/workshop',{method:'POST',body:{action:'asset',name,number,category,registration}}),()=>{setNewAsset(false);setName('');data.refresh();});}}>
 <label>Asset name<input required className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></label><label>Asset number<input className={inputClass} value={number} onChange={e=>setNumber(e.target.value)}/></label><label>Category<input className={inputClass} value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Registration<input className={inputClass} value={registration} onChange={e=>setRegistration(e.target.value)}/></label><button disabled={action.busy} className={inputClass}>Save asset</button></form>}
 <div className="grid gap-3 sm:grid-cols-3">{data.data?.assets.map(a=><button key={a.id} onClick={()=>setAssetId(a.id)} className={`rounded-lg border p-3 text-left ${assetId===a.id?'border-orange-500 bg-orange-50':''}`}><strong>{a.name}</strong><p className="text-xs">{a.plant_number}</p>{a.current_meter!=null&&<p className="text-xs">{a.current_meter} {a.meter_type}{a.next_service_meter!=null?` · service at ${a.next_service_meter}`:''}{a.next_service_date?` · service by ${a.next_service_date}`:''}</p>}{a.service.overdue&&<Pill tone="warning">Service overdue</Pill>}<Pill tone={a.status==='Out of service'?'danger':'neutral'}>{a.status}</Pill></button>)}</div>{!data.data?.assets.length&&<p>Add your first asset to start recording defects and repairs.</p>}
 </Section>
 {assetId&&data.data?.assets.find(x=>x.id===assetId)&&<ServicePanel key={assetId+':'+data.data.assets.find(x=>x.id===assetId)!.revision} asset={data.data.assets.find(x=>x.id===assetId)!} readings={data.data.readings} events={data.data.services} today={data.data.today} editable={editable} canCorrect={Boolean(data.data.canCorrect)&&session.writable('workshop')} refresh={data.refresh}/>}
 {assetId&&session.module('ims')&&session.can('forms.view')&&<><FormLauncher context={{type:'asset',id:assetId,label:data.data?.assets.find(a=>a.id===assetId)?.name||'this asset'}} hint="Prestarts and inspections for the selected asset. Defects found are raised from the submitted form."/><SubmissionList key={assetId} context={{type:'asset',id:assetId,label:data.data?.assets.find(a=>a.id===assetId)?.name||''}}/></>}
 {editable&&<Section title="Report defect" description="Critical defects immediately take the asset out of service. They remain blocked until independently verified."><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save({action:'defect',assetId,title,note,severity});}}>
 <label>Asset<select required className={inputClass} value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">Choose asset</option>{data.data?.assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Severity<select className={inputClass} value={severity} onChange={e=>setSeverity(e.target.value)}>{['minor','major','critical'].map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Defect<input required maxLength={180} className={inputClass} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Inspection evidence / description<textarea required className={inputClass} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={action.busy} className={inputClass}>Create work order</button></form></Section>}
 <Section title="Work orders"><div className="space-y-2">{data.data?.orders.map(o=><button key={o.id} onClick={()=>{setSelected(o.id);setRepairNote('');}} className="flex w-full flex-wrap justify-between gap-2 rounded-lg border p-3 text-left"><span>{o.title}<small className="block">{data.data?.assets.find(a=>a.id===o.asset_id)?.name} · {o.severity}{o.source_type==='form_submission'?' · raised from a form':''}</small></span><Pill>{o.status.replaceAll('_',' ')}</Pill></button>)}{!data.data?.orders.length&&<p>No defects recorded.</p>}</div></Section>
 {order&&<Section title={order.title} description="History is append-only. Repairs must be verified by a different authorised person.">{order.source_type==='form_submission'&&<OrderSource orderId={order.id}/>}<ol className="mb-4 space-y-3">{data.data?.entries.filter(e=>e.order_id===order.id).map(e=><li key={e.id} className="rounded border p-3"><strong>{e.kind}</strong><small className="ml-2">{new Date(e.created_at).toLocaleString()}</small><p className="whitespace-pre-wrap">{e.note}</p>{e.parts&&<p>Parts: {e.parts}</p>}{e.labour_hours!=null&&<p>Labour: {e.labour_hours} hours</p>}</li>)}</ol>
 {order.status!=='closed'&&<div className="space-y-3"><label>Repair / verification notes<textarea className={inputClass} value={repairNote} onChange={e=>setRepairNote(e.target.value)}/></label>
 {editable&&['open','rework'].includes(order.status)&&<><label>Labour hours<input type="number" min="0" step="0.25" className={inputClass} value={hours} onChange={e=>setHours(e.target.value)}/></label><label>Parts / external repair<textarea className={inputClass} value={parts} onChange={e=>setParts(e.target.value)}/></label><Btn disabled={action.busy||!repairNote.trim()} onClick={()=>void save({action:'repair',id:order.id,revision:order.revision,note:repairNote,labourHours:Number(hours),parts})}>Complete repair for verification</Btn></>}
 {verify&&order.status==='awaiting_verification'&&<div className="flex gap-3">{[true,false].map(accepted=><Btn key={String(accepted)} disabled={action.busy||!repairNote.trim()} onClick={()=>void save({action:'verify',id:order.id,revision:order.revision,note:repairNote,accepted})}>{accepted?'Verify repair':'Return for rework'}</Btn>)}</div>}</div>}
 </Section>}</div>;
}
