ALTER TABLE dockets ADD COLUMN organisation_id TEXT NOT NULL DEFAULT 'roadworx-sydney';
CREATE INDEX IF NOT EXISTS idx_dockets_organisation ON dockets(organisation_id);
CREATE TABLE IF NOT EXISTS organisations (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL);
INSERT OR IGNORE INTO organisations (id,name,created_at) VALUES ('roadworx-sydney','Roadworx Surfacing Pty Ltd',datetime('now'));
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, email TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_users_org ON users(organisation_id);
CREATE TABLE IF NOT EXISTS clients (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, contact_name TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS idx_clients_org ON clients(organisation_id);
CREATE TABLE IF NOT EXISTS opportunities (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_opportunities_org ON opportunities(organisation_id);
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_jobs_org ON jobs(organisation_id);
CREATE TABLE IF NOT EXISTS work_packages (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_work_packages_org ON work_packages(organisation_id);
CREATE TABLE IF NOT EXISTS estimates (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_estimates_org ON estimates(organisation_id);
CREATE TABLE IF NOT EXISTS quote_revisions (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_quote_revisions_org ON quote_revisions(organisation_id);
CREATE TABLE IF NOT EXISTS cost_codes (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_cost_codes_org ON cost_codes(organisation_id);
CREATE TABLE IF NOT EXISTS rate_libraries (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_rate_libraries_org ON rate_libraries(organisation_id);
CREATE TABLE IF NOT EXISTS shifts (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_shifts_org ON shifts(organisation_id);
CREATE TABLE IF NOT EXISTS workers (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_workers_org ON workers(organisation_id);
CREATE TABLE IF NOT EXISTS crews (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_crews_org ON crews(organisation_id);
CREATE TABLE IF NOT EXISTS plant (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_plant_org ON plant(organisation_id);
CREATE TABLE IF NOT EXISTS suppliers (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_suppliers_org ON suppliers(organisation_id);
CREATE TABLE IF NOT EXISTS subcontractors (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_subcontractors_org ON subcontractors(organisation_id);
CREATE TABLE IF NOT EXISTS variations (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_variations_org ON variations(organisation_id);
CREATE TABLE IF NOT EXISTS qa_safety_records (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_qa_safety_records_org ON qa_safety_records(organisation_id);
CREATE TABLE IF NOT EXISTS attachments (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_attachments_org ON attachments(organisation_id);
CREATE TABLE IF NOT EXISTS commercial_records (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_commercial_records_org ON commercial_records(organisation_id);
CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, organisation_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_audit_events_org ON audit_events(organisation_id);
