'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {authClient} from '@/lib/platform/auth-client';

type Role='admin'|'office'|'field';
type Me={userId:string;email:string;role:Role;emailEnabled:boolean};
type Member={id:string;name:string;email:string;role:Role;active:boolean};
type State={role:Role;active:boolean};
type Event={id:string;created_at:string;metadata:{actorEmail:string;email:string;before:State;after:State}};
const roles:Role[]=['admin','office','field'];
const label=(r:string)=>r.charAt(0).toUpperCase()+r.slice(1);
const descriptions={admin:'Full access, team management, settings and rate libraries.',office:'Operational and commercial records, pricing and approvals. No team or admin settings.',field:'Shift records, quantities, site evidence and approved assigned-job documents. No financial data.'};
const control='min-h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm disabled:opacity-50';
async function json(url:string,init?:RequestInit){const r=await fetch(url,{cache:'no-store',...init});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'Request failed.'),{status:r.status});return data;}
export default function Account(){
 const [me,setMe]=useState<Me>(),[members,setMembers]=useState<Member[]>([]),[events,setEvents]=useState<Event[]>([]),[drafts,setDrafts]=useState<Record<string,State>>({}),[pending,setPending]=useState<{member:Member;next:State}|null>(null);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const refresh=useCallback(async()=>{
  try{const account:Me=await json('/api/invitations');setError('');setMe(account);if(account.role==='admin'){const team=await json('/api/team');setMembers(team.members);setEvents(team.events);setDrafts({});}}
  catch(e){const err=e as Error&{status?:number};if(err.status===401){location.assign('/login');return;}setError(err.status===403?'Your workspace access is inactive. Contact an organisation admin to reactivate it.':err.message);}
  finally{setLoading(false);}
 },[]);
 // refresh only updates state after the account request resolves or rejects.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void refresh();},[refresh]);
 async function save(){if(!pending)return;setBusy(true);setError('');try{const result=await json('/api/team',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:pending.member.id,expected:{role:pending.member.role,active:pending.member.active},next:pending.next})});setPending(null);if(result.selfChanged){location.assign('/');return;}await refresh();setMessage('Team access updated.');}catch(e){setError((e as Error).message);setPending(null); }finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#f6f7f9] p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-5xl space-y-6">
  <Link href="/" className="text-sm text-slate-500 hover:underline">← Back to workspace</Link>
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-medium uppercase tracking-wider text-slate-500">Organisation access</p><h1 className="text-3xl font-semibold tracking-tight">{me?.role==='admin'?'Team & permissions':'Your account'}</h1><p className="mt-2 text-sm text-slate-500">{me?`${me.email} · ${label(me.role)}`:'Manage your workspace access.'}</p></div><button className={control} onClick={async()=>{await authClient.signOut();location.assign('/login')}}>Sign out</button></header>
  {loading&&<p role="status">Loading your account…</p>}{error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}<button className="ml-3 underline" onClick={()=>void refresh()}>Refresh</button></div>}{message&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{message}</p>}
  {me&&<section className="grid gap-3 sm:grid-cols-3" aria-label="Role permissions">{roles.map(role=><article key={role} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{label(role)}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{descriptions[role]}</p></article>)}</section>}
  {me?.role==='admin'&&<>
   <section className="overflow-hidden rounded-xl border bg-white"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Team members</h2><p className="mt-1 text-xs text-slate-500">Deactivate access without deleting records or history. Keep at least one active admin.</p></div><button className={control} disabled={busy} onClick={()=>void refresh()}>Refresh</button></div>
    <div className="divide-y">{members.map(member=>{const draft=drafts[member.id]||{role:member.role,active:member.active},changed=draft.role!==member.role||draft.active!==member.active,lastAdmin=member.active&&member.role==='admin'&&members.filter(m=>m.active&&m.role==='admin').length===1;return <div key={member.id} className="flex flex-wrap items-center gap-4 p-5"><div className="min-w-0 flex-1 basis-48"><p className="font-medium">{member.name}{member.id===me.userId&&<span className="ml-2 text-xs text-slate-400">You</span>}</p><p className="break-all text-sm text-slate-500">{member.email}</p><p className={`mt-1 text-xs ${member.active?'text-emerald-700':'text-slate-500'}`}>{member.active?'Active':'Inactive'}{lastAdmin?' · Last active admin':''}</p></div><label className="grid gap-1 text-xs text-slate-500">Role<select className={control} aria-label={`Role for ${member.email}`} disabled={busy||lastAdmin} value={draft.role} onChange={e=>setDrafts({...drafts,[member.id]:{...draft,role:e.target.value as Role}})}>{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><label className="grid gap-1 text-xs text-slate-500">Access<select className={control} aria-label={`Access for ${member.email}`} disabled={busy||lastAdmin} value={draft.active?'active':'inactive'} onChange={e=>setDrafts({...drafts,[member.id]:{...draft,active:e.target.value==='active'}})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className={`${control} mt-5 bg-slate-900 text-white`} disabled={busy||!changed} onClick={()=>{setError('');setMessage('');setPending({member,next:draft});}}>Review change</button></div>;})}</div>
   </section>
   {pending&&<section role="alertdialog" aria-modal="false" aria-labelledby="change-title" className="rounded-xl border-2 border-orange-300 bg-orange-50 p-5"><h2 id="change-title" className="font-semibold">Confirm access change</h2><p className="my-3 text-sm">{pending.member.email}: {label(pending.member.role)} / {pending.member.active?'Active':'Inactive'} → {label(pending.next.role)} / {pending.next.active?'Active':'Inactive'}. {!pending.next.active?'Their sessions will be revoked and workspace access blocked.':'Their permissions will apply on the next request.'} {pending.member.id===me.userId?'This changes your own access.':''}</p><div className="flex gap-3"><button autoFocus className={control} disabled={busy} onClick={()=>setPending(null)}>Cancel</button><button className={`${control} bg-orange-600 text-white`} disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Confirm change'}</button></div></section>}
   <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Invite a colleague</h2>{me.emailEnabled?<form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');setMessage('');try{await json('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),role:f.get('role')})});setMessage('Invitation emailed.');form.reset();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="grid flex-1 gap-1 text-sm">Email address<input className={control} disabled={busy} name="email" type="email" required/></label><label className="grid gap-1 text-sm">Role<select className={control} name="role" disabled={busy} defaultValue="field">{roles.map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><button className={`${control} bg-slate-900 text-white`} disabled={busy}>Send invitation</button></form>:<p className="mt-2 text-sm leading-6 text-slate-500">Email is switched off, so invitations are unavailable. You can manage existing members here. A separate signup creates its own organisation; it does not join this team.</p>}</section>
   <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Recent access changes</h2>{!events.length?<p className="mt-3 text-sm text-slate-500">No access changes recorded yet.</p>:<ul className="mt-3 divide-y">{events.map(e=><li key={e.id} className="py-3 text-sm"><p>{e.metadata.email}: {label(e.metadata.before.role)} / {e.metadata.before.active?'Active':'Inactive'} → {label(e.metadata.after.role)} / {e.metadata.after.active?'Active':'Inactive'}</p><p className="mt-1 text-xs text-slate-500">{e.metadata.actorEmail} · {new Date(e.created_at).toLocaleString('en-AU')}</p></li>)}</ul>}</section>
  </>}
  {me&&!me.emailEnabled&&<p className="text-xs text-slate-500">Email password recovery is switched off. Keep your password in a password manager.</p>}
 </div></main>;
}
