'use client';
import {FieldPreparation} from '@/components/field-preparation';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {initialField,incomplete,fieldMetrics,hours,resourceHours,type FieldData,type FieldRecord,type Row} from '@/lib/field';
import { OperationsPage } from '@/components/operations-workspace';
import type {DeliveryRecord} from '@/lib/planning';
type User={role:string;id:string;email:string;priced?:boolean;canSubmit:boolean;canAmend:boolean};
type History={revision:number;action:string;reason:string;actor:string;snapshot:string;created_at:string};
type Spec=[string,string,string?];
const sections:Record<string,Spec[]>={
 delays:[['start','Start','datetime-local'],['finish','Finish','datetime-local'],['cause','Cause'],['party','Responsible party']],
 cycles:[['truck','Truck / registration'],['start','Cycle start','datetime-local'],['finish','Cycle finish','datetime-local'],['waitStart','Waiting start','datetime-local'],['waitFinish','Waiting finish','datetime-local'],['tonnes','Load tonnes','number']],
 checks:[['time','Check time','datetime-local'],['temperature','Asphalt temperature °C','number'],['location','Load / chainage'],['result','Production check and result'],['action','Corrective action']],
 instructions:[['time','Time','datetime-local'],['representative','Client representative'],['details','Instruction']],
 standDowns:[['start','Start','datetime-local'],['finish','Finish','datetime-local'],['reason','Reason'],['party','Responsible party']],
 incidents:[['time','Time','datetime-local'],['type','Incident / hazard'],['details','Details'],['action','Action / notification']],
 variations:[['description','Description'],['instructionBy','Instructed by / reference'],['cost','Estimated additional cost','number'],['status','Approval status']]
};
function Signature({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),moved=useRef(false);
 return <div className="space-y-2"><p className="font-medium">{label}</p>{value?<><img src={value} alt={label} className="h-28 w-full rounded border bg-white object-contain"/><Button type="button" variant="outline" onClick={()=>onChange('')}>Clear signature</Button></>:<canvas ref={canvas} width={600} height={200} aria-label={label} className="h-32 w-full touch-none rounded border-2 border-slate-300 bg-white" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;moved.current=false;const c=canvas.current!,r=c.getBoundingClientRect(),ctx=c.getContext('2d')!;ctx.beginPath();ctx.moveTo((e.clientX-r.left)*600/r.width,(e.clientY-r.top)*200/r.height);}} onPointerMove={e=>{if(!drawing.current)return;moved.current=true;const c=canvas.current!,r=c.getBoundingClientRect(),ctx=c.getContext('2d')!;ctx.lineWidth=3;ctx.lineCap='round';ctx.lineTo((e.clientX-r.left)*600/r.width,(e.clientY-r.top)*200/r.height);ctx.stroke();}} onPointerUp={()=>{drawing.current=false;if(moved.current)onChange(canvas.current!.toDataURL('image/png'));}} onPointerCancel={()=>{drawing.current=false;}}/>}</div>;
}
type ApiResult={error?:string;requirements?:string[];shifts:DeliveryRecord[];jobs:DeliveryRecord[];user:User;record:FieldRecord|null;history:History[];records:{shift_id:string;status:string}[]};
async function api(url:string,body?:unknown){const res=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await res.json() as ApiResult;if(!res.ok)throw new Error([data.error,...(data.requirements||[])].join('\n'));return data;}
export function FieldWorkspace(){
 const [legacy,setLegacy]=useState(false);
 const [shifts,setShifts]=useState<DeliveryRecord[]>([]),[jobs,setJobs]=useState<DeliveryRecord[]>([]),[user,setUser]=useState<User|null>(null),[statuses,setStatuses]=useState<Record<string,string>>({});
 const [date,setDate]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[supervisor,setSupervisor]=useState('');
 const [selected,setSelected]=useState<DeliveryRecord|null>(null),[record,setRecord]=useState<FieldRecord|null>(null),[draft,setDraft]=useState<FieldData|null>(null),[history,setHistory]=useState<History[]>([]),[review,setReview]=useState(false),[amending,setAmending]=useState(false),[reason,setReason]=useState('');
 const [message,setMessage]=useState('Loading shifts…'),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[conflict,setConflict]=useState(false),[storageError,setStorageError]=useState('');
 const current=useRef<{draft:FieldData|null;record:FieldRecord|null;shift:DeliveryRecord|null;version:number}>({draft:null,record:null,shift:null,version:0});
 const saving=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function keep(d:FieldData,r:FieldRecord|null,s:DeliveryRecord){try{localStorage.setItem(`field:${user?.id}:${s.id}`,JSON.stringify({data:d,revision:r?.revision||0,amending,reason}));setStorageError('');}catch{setStorageError('Device backup unavailable. Save online before leaving this page.');}}
 useEffect(()=>{Promise.all([api('/api/delivery'),api('/api/field')]).then(([d,f])=>{setShifts(d.shifts);setJobs(d.jobs);setUser(f.user);setStatuses(Object.fromEntries(f.records.map((r:{shift_id:string;status:string})=>[r.shift_id,r.status])));setMessage('');}).catch(e=>setMessage(e.message));return()=>{if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function open(s:DeliveryRecord){setBusy(true);try{const f=await api(`/api/field?shiftId=${encodeURIComponent(s.id)}`);let d=f.record?.data||initialField(s);let recovered=false,clash=false;const raw=localStorage.getItem(`field:${user?.id}:${s.id}`);let amendRecovered=false,amendReason='';if(raw){const local=JSON.parse(raw);if(f.record?.status!=='Submitted'||(local.amending&&local.revision===f.record?.revision)){amendRecovered=!!local.amending;amendReason=local.reason||'';d=local.data;recovered=JSON.stringify(d)!==JSON.stringify(f.record?.data);clash=local.revision!==(f.record?.revision||0)&&recovered;}}setSelected(s);setRecord(f.record);setDraft(d);setHistory(f.history);setUser(f.user);setReview(false);setAmending(amendRecovered);setReason(amendReason);setConflict(clash);setDirty(recovered);current.current={draft:d,record:f.record,shift:s,version:0};setMessage(clash?'A newer server revision exists. Your device draft is shown. Download it, then reload the server record to reconcile.':recovered?'Recovered device draft. Save when ready.':'');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 async function save(action='save'){
 if(timer.current)clearTimeout(timer.current);
 const c=current.current;if(!c.draft||!c.shift||saving.current||conflict)return;saving.current=true;setBusy(true);setMessage('Saving…');const version=c.version;
 try{const f=await api('/api/field',{shiftId:c.shift.id,revision:c.record?.revision||0,action,reason,data:c.draft});if(!f.record)throw new Error("Saved record missing");const savedStatus=f.record.status;current.current.record=f.record;setRecord(f.record);setStatuses(v=>({...v,[c.shift!.id]:savedStatus}));if(current.current.version===version){setDirty(false);setMessage(action==='save'?'All changes saved':action==='amend'?'Amendment submitted; original retained':'Shift submitted and locked');}else setMessage('Earlier changes saved; newer edits remain on this device.');keep(current.current.draft!,f.record,c.shift);if(action!=='save'){setAmending(false);setReview(true);const h=await api(`/api/field?shiftId=${c.shift.id}`);setHistory(h.history);localStorage.removeItem(`field:${user?.id}:${c.shift.id}`);}}
 catch(e){const msg=String(e);setMessage(msg);if(/another|changed|reconcile/i.test(msg))setConflict(true);}finally{saving.current=false;setBusy(false);}
 }
 function change(next:FieldData){setDraft(next);current.current.draft=next;current.current.version++;setDirty(true);if(selected)keep(next,current.current.record,selected);setMessage('Changes saved on this device');if(timer.current)clearTimeout(timer.current);if(!amending&&!conflict)timer.current=setTimeout(()=>{void save();},1200);}
 function patch(key:keyof FieldData,value:unknown){const next={...current.current.draft!,[key]:value};if(!['clientSignature','supervisorSignature','clientName','supervisorName','clientDeclinedReason'].includes(key)){next.clientSignature='';next.supervisorSignature='';}change(next);}
 const financial=Boolean(user?.priced);
 const locked=record?.status==='Submitted'&&!amending;
 const plan=record?.plan||selected,job=record?.job||jobs.find(j=>j.id===selected?.metadata.jobId);
 const metrics=draft&&plan&&job?fieldMetrics(draft,plan,job):null;
 function input(key:keyof FieldData,label:string,type='text'){return <label key={key} className="block space-y-1 text-sm"><span>{label}</span><Input type={type} step={type==='number'?'any':undefined} value={String(draft?.[key]??'')} onChange={e=>patch(key,e.target.value)}/></label>;}
 function rows(key:keyof FieldData,title:string,specs:Spec[]){const list=draft![key] as Row[];return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer py-2 font-semibold">{title} <span className="text-slate-500">({list.length})</span></summary><div className="mt-3 space-y-3">{list.map((r,i)=><div key={i} className="space-y-3 rounded-lg border bg-slate-50 p-3"><div className="grid gap-3 sm:grid-cols-2">{specs.filter(([k])=>financial||k!=='cost').map(([k,label,type])=><label key={k} className="text-sm">{label}<Input type={type||'text'} step="any" value={String(r[k]??'')} onChange={e=>patch(key,list.map((v,n)=>n===i?{...v,[k]:e.target.value}:v))}/></label>)}</div>{r.start&&r.finish?<p className="text-sm">Duration: {hours(r.start,r.finish).toFixed(2)} h</p>:null}{key==='cycles'&&<p className="text-sm">Waiting: {hours(r.waitStart,r.waitFinish).toFixed(2)} h</p>}<Button type="button" variant="outline" onClick={()=>patch(key,list.filter((_,n)=>n!==i))}>Remove entry {i+1}</Button></div>)}<Button type="button" variant="outline" onClick={()=>patch(key,[...list,{}])}>+ Add {title.toLowerCase()}</Button></div></details>;}
 async function upload(files:FileList|null){if(!files)return;setBusy(true);try{for(const file of Array.from(files)){const form=new FormData();form.append('file',file);const res=await fetch('/api/delivery/documents',{method:'POST',body:form});const f=await res.json() as {id:string;name:string;url:string;error?:string};if(!res.ok)throw new Error(f.error);patch('attachments',[...current.current.draft!.attachments,f]);}setMessage('Attachments uploaded and added to your draft');}catch(e){setMessage(`Upload failed: ${String(e)}. Select the file again to retry.`);}finally{setBusy(false);}}
 function exportDraft(){const blob=new Blob([JSON.stringify(current.current.draft,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`field-draft-${selected?.id}.json`;a.click();URL.revokeObjectURL(a.href);}
 if(legacy)return <div><Button variant="outline" onClick={()=>setLegacy(false)}>Back to daily shifts</Button><OperationsPage module="Field" onNavigate={()=>setLegacy(false)}/></div>;
 return <div className="field-workspace mx-auto max-w-4xl space-y-4 pb-24"><style>{`.field-workspace input,.field-workspace select,.field-workspace textarea{min-height:48px;font-size:16px;max-width:100%;min-width:0}.field-workspace button{min-height:48px;white-space:normal}.field-workspace input[type=datetime-local]{width:100%}.field-workspace summary{min-height:48px}.field-workspace fieldset:disabled{opacity:.8}`}</style>
 <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold">{selected?'Daily shift record':'Field shifts'}</h2>{selected&&<Button variant="outline" disabled={busy} onClick={()=>{if(timer.current)clearTimeout(timer.current);setSelected(null);setDraft(null);setReview(false);}}>Back to shifts</Button>}</div>
 {record?.data.pricingReviewRequired&&financial&&<p className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm">Office pricing review required. This field submission has unpriced costs or resources; complete an authorised amendment before relying on its cost totals.</p>}{!financial&&<p className="text-sm text-slate-500">Record work, quantities and site evidence here. Office staff manage pricing and commercial approvals.</p>}{message&&<p role="status" className="whitespace-pre-line rounded-lg border bg-white p-3 text-sm">{message}</p>}{storageError&&<p role="alert" className="text-red-700">{storageError}</p>}
 {!selected?<>{financial&&<Button variant="outline" onClick={()=>setLegacy(true)}>Previous field work fronts</Button>}<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Shift date<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="text-sm">Assigned supervisor / crew<Input placeholder="Filter name or leave blank for all" value={supervisor} onChange={e=>setSupervisor(e.target.value)}/></label></div>{shifts.filter(s=>s.metadata.date===date&&JSON.stringify([s.metadata.supervisor,s.metadata.assignments]).toLowerCase().includes(supervisor.toLowerCase())).map(s=><button key={s.id} disabled={busy||['Draft','Cancelled'].includes(s.status)} className="block w-full rounded-xl border bg-white p-4 text-left disabled:opacity-50" onClick={()=>void open(s)}><strong>{s.name}</strong><span className="mt-1 block text-sm">{String(s.metadata.start)}–{String(s.metadata.finish)} · {String(s.metadata.location||'')} · {String(s.metadata.supervisor||'Unassigned supervisor')}</span><span className="mt-2 block font-medium text-orange-700">{statuses[s.id]||s.status} · Open shift →</span></button>)}{!shifts.some(s=>s.metadata.date===date)&&<p className="rounded-xl border border-dashed p-6">No shifts planned for this date. Create a shift in Planning or choose another date.</p>}</>:draft&&<>
 <FieldPreparation shiftId={selected.id}/><section className="rounded-xl bg-[#101a24] p-4 text-white"><h3 className="font-bold">{selected.name}</h3><p className="text-sm">{String(plan?.metadata.date)} · {String(plan?.metadata.start)}–{String(plan?.metadata.finish)} · {record?.status||'Not yet saved'}</p><p className="mt-2 text-sm">{String(plan?.metadata.scope||'')}</p><p className="mt-2 text-sm">{String(plan?.metadata.instructions||'')}</p>{plan?.metadata.preStart?<p className="mt-2 text-sm">Pre-start: {String(plan.metadata.preStart)}</p>:null}<p className="mt-2 text-sm">Client: {String(plan?.metadata.siteContact||'Not assigned')}</p></section>
 {conflict&&<div className="space-y-2 rounded border border-amber-500 p-4"><Button variant="outline" onClick={exportDraft}>Download retained draft</Button><Button variant="outline" onClick={()=>{localStorage.removeItem(`field:${user?.id}:${selected.id}`);void open(selected);}}>Reload server record</Button><p className="text-sm">Download your draft before reloading. Re-enter the differences against the latest server record.</p></div>}
 <div className="flex gap-2"><Button variant={!review?'default':'outline'} onClick={()=>setReview(false)}>Shift entry</Button><Button variant={review?'default':'outline'} onClick={()=>setReview(true)}>End-of-shift review</Button></div>
 {locked&&<div className="rounded-lg border bg-orange-50 p-4"><p>Submitted record locked. Changes require a manager or administrator and an amendment reason.</p>{user?.canAmend&&<Button className="mt-3" onClick={()=>{setAmending(true);setReview(false);setMessage('Amendment draft stays on this device until submitted.');}}>Start authorised amendment</Button>}</div>}
 {amending&&<label className="block font-medium">Reason for amendment<Textarea value={reason} onChange={e=>{setReason(e.target.value);try{localStorage.setItem(`field:${user?.id}:${selected.id}`,JSON.stringify({data:draft,revision:record?.revision||0,amending:true,reason:e.target.value}));}catch{setStorageError('Amendment reason could not be backed up on device.');}}} placeholder="Explain why the original needs to be changed"/></label>}
 {!review?<fieldset disabled={locked||busy||conflict} className="space-y-4">
 <section className="space-y-4 rounded-xl border bg-white p-4"><h3 className="font-semibold">Site and pre-start</h3><div className="grid gap-3 sm:grid-cols-2">{input('arrival','Actual site arrival','datetime-local')}{input('departure','Actual site departure','datetime-local')}</div><label className="flex min-h-12 items-center gap-3"><Checkbox checked={draft.preStart} onCheckedChange={v=>patch('preStart',v===true)}/>Pre-start completed</label><label className="block text-sm">Pre-start notes<Textarea value={draft.preStartNotes} onChange={e=>patch('preStartNotes',e.target.value)}/></label></section>
 <details open className="rounded-xl border bg-white p-4"><summary className="cursor-pointer py-2 font-semibold">Crew, attendance, plant and trucks</summary><p className="text-sm text-slate-600">Confirm each planned resource. Enter actual times or hours; breaks are deducted. Record attendance and quantities; office staff reconcile costs.</p><div className="mt-3 space-y-3">{draft.resources.map((r,i)=><div className="space-y-3 rounded-lg border p-3" key={i}><strong>{String(r.name)||'Additional resource'}{r.additional?' · additional':''}</strong><div className="grid gap-3 sm:grid-cols-2">{(['name','category','role','attendance','start','finish','breakMinutes','hours','rate','trips'] as const).filter(k=>financial||k!=='rate').map(k=><label key={k} className="text-sm">{{name:'Name / asset',category:'Category',role:'Role (Truck for trucking)',attendance:'Attendance / use',start:'Actual start',finish:'Actual finish',breakMinutes:'Unpaid break minutes',hours:'Actual hours (if no times)',rate:'Cost per hour',trips:'Trips'}[k]}{['attendance','category'].includes(k)?<NativeSelect value={String(r[k])} onChange={e=>patch('resources',draft.resources.map((v,n)=>n===i?{...v,[k]:e.target.value}:v))}>{(k==='attendance'?['Unconfirmed','Present','Absent','Used','Not used']:['workers','crews','plant','suppliers','subcontractors']).map(v=><NativeSelectOption key={v} value={v}>{v}</NativeSelectOption>)}</NativeSelect>:<Input type={['start','finish'].includes(k)?'datetime-local':['hours','rate','trips','breakMinutes'].includes(k)?'number':'text'} step="any" value={String(r[k]??'')} onChange={e=>patch('resources',draft.resources.map((v,n)=>n===i?{...v,[k]:e.target.value}:v))}/>}</label>)}</div><p className="text-sm">Actual paid / used hours: {resourceHours(r).toFixed(2)}</p>{r.additional&&<Button variant="outline" onClick={()=>patch('resources',draft.resources.filter((_,n)=>n!==i))}>Remove additional resource</Button>}</div>)}<Button variant="outline" onClick={()=>patch('resources',[...draft.resources,{name:'',category:'workers',role:'Worker',attendance:'Unconfirmed',hours:'',rate:'',additional:true}])}>+ Additional resource</Button></div></details>
 <details open className="rounded-xl border bg-white p-4"><summary className="cursor-pointer py-2 font-semibold">Production and quantities</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{input('productionStart','Production start','datetime-local')}{input('productionFinish','Production finish','datetime-local')}{input('tonnes','Tonnes placed','number')}{input('loads','Loads','number')}{input('trips','Total truck trips','number')}{input('area','Area completed (m²)','number')}{input('chainage','Chainage completed')}{input('wastage','Material wastage (t)','number')}{input('wastageReason','Wastage reason')}{financial&&<>{input('materialCost','Actual total material cost incl. wastage ($)','number')}{input('otherCost','Other actual costs excl. resources/materials ($)','number')}</>}</div></details>
 {Object.entries(sections).map(([key,specs])=><div key={key}>{rows(key as keyof FieldData,{delays:'Delays',cycles:'Truck cycles',checks:'Temperature and production checks',instructions:'Client instructions',standDowns:'Stand-downs',incidents:'Incidents and hazards',variations:'Variations'}[key]!,specs)}</div>)}
 <section className="space-y-3 rounded-xl border bg-white p-4"><h3 className="font-semibold">Photos and attachments</h3><label className="block rounded-lg border p-3 text-sm">Take site photo<Input type="file" accept="image/*" capture="environment" onChange={e=>{void upload(e.target.files);e.target.value='';}}/></label><label className="block rounded-lg border p-3 text-sm">Add photos or documents (20 MB each)<Input type="file" multiple onChange={e=>{void upload(e.target.files);e.target.value='';}}/></label>{draft.attachments.map(a=><div key={a.id} className="flex items-center justify-between gap-2"><a className="break-all text-primary underline" href={a.url} target="_blank" rel="noreferrer">{a.name}</a><Button variant="outline" onClick={()=>patch('attachments',draft.attachments.filter(v=>v.id!==a.id))}>Remove</Button></div>)}</section>
 <section className="space-y-4 rounded-xl border bg-white p-4"><label className="block font-semibold">Site diary notes<Textarea rows={5} value={draft.diary} onChange={e=>patch('diary',e.target.value)}/></label><label className="flex min-h-12 items-center gap-3"><Checkbox checked={draft.reviewed} onCheckedChange={v=>patch('reviewed',v===true)}/>Delays, stand-downs, instructions, incidents and variations reviewed; empty sections mean none to report.</label>{input('clientName','Client representative')}<Signature label="Client digital sign-off" value={draft.clientSignature} onChange={v=>patch('clientSignature',v)}/>{input('clientDeclinedReason','If client cannot sign, record reason')}{input('supervisorName','Supervisor name')}<Signature label="Supervisor digital sign-off" value={draft.supervisorSignature} onChange={v=>patch('supervisorSignature',v)}/><p className="text-sm">Signatures confirm this shift record. Submission records the authenticated supervisor and time. Client sign-off does not approve variation pricing.</p></section>
 </fieldset>:<section className="space-y-4 rounded-xl border bg-white p-4"><h3 className="text-lg font-bold">End-of-shift review</h3>{incomplete(draft,financial).length?<div className="rounded-lg bg-amber-50 p-3"><p className="font-semibold">Complete before submission</p><ul className="ml-5 list-disc text-sm">{incomplete(draft,financial).map((v,i)=><li key={i}>{v}</li>)}</ul></div>:<p className="rounded bg-green-50 p-3 text-green-800">All required entries complete.</p>}{metrics&&<><div className="space-y-2">{metrics.rows.filter(([label])=>financial||label!=='Shift cost ($)').map(([label,p,a])=><div key={label} className="rounded border p-3"><p className="font-medium">{label}</p><div className="mt-1 flex flex-wrap justify-between gap-2 text-sm"><span>Plan {p.toFixed(2)}</span><span>Actual {a.toFixed(2)}</span><span className={a>p?'text-orange-700':''}>Δ {(a-p).toFixed(2)}</span></div></div>)}</div><p>Total truck waiting: {metrics.waiting.toFixed(2)} h</p>{financial&&<><p>Forecast job margin effect: {metrics.marginEffect===null?'Unavailable — contract value missing':`${metrics.marginEffect.toFixed(2)} percentage points`}</p><p className="text-sm text-slate-600">Effect isolates this shift’s cost difference against contract revenue, holding other work and revenue unchanged. Plan production rate uses planned shift hours. Actual uses the production interval. Delay totals are event-hours and can overlap. Costs include actual resources plus entered material and other costs; provisional until reconciled with dockets.</p></>}</>}{!locked&&<Button className="w-full" disabled={busy||conflict||incomplete(draft,financial).length>0||(!amending&&!user?.canSubmit)||(amending&&!reason.trim())} onClick={()=>void save(amending?'amend':'submit')}>{amending?'Submit authorised amendment':'Supervisor: submit and lock shift'}</Button>}{!user?.canSubmit&&<p className="text-sm">A supervisor must submit the completed record.</p>}</section>}
 {history.length>0&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Audit history ({history.length} revisions)</summary>{history.map(h=><div key={h.revision} className="border-b py-3 text-sm"><p>Revision {h.revision} · {h.action} · {new Date(h.created_at).toLocaleString('en-AU')}</p><p>{JSON.parse(h.actor).email} {h.reason?`— ${h.reason}`:''}</p><details><summary>View saved snapshot</summary><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(JSON.parse(h.snapshot),null,2)}</pre></details></div>)}</details>}
 {!locked&&<div className="sticky bottom-2 flex flex-wrap items-center justify-between gap-2 rounded-xl border bg-white p-3 shadow-lg"><span className="text-sm">{dirty?'Unsaved server changes':record?'Saved':'New record'}</span><Button disabled={busy||conflict} variant="outline" onClick={()=>amending?exportDraft():void save()}>{amending?'Download amendment draft':'Save progress'}</Button><Button onClick={()=>{setReview(true);window.scrollTo({top:0,behavior:'smooth'});}}>Review shift</Button></div>}
 </>}
 </div>;
}
