'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import type {PreparationRecord} from '@/lib/preparation';
export function FieldPreparation({shiftId}:{shiftId:string}){
 const [documents,setDocuments]=useState<PreparationRecord[]>([]),[error,setError]=useState(''),[activity,setActivity]=useState(''),[result,setResult]=useState(''),[attachmentId,setAttachmentId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;fetch(`/api/preparation/field?shiftId=${encodeURIComponent(shiftId)}`).then(async r=>{const data=await r.json() as {documents:PreparationRecord[];error?:string};if(!r.ok)throw new Error(data.error);if(active)setDocuments(data.documents);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[shiftId]);
 async function record(doc:PreparationRecord,rowId:string,action:string){setBusy(true);try{const r=await fetch('/api/preparation/field',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shiftId,documentId:doc.id,revision:doc.revision,rowId,result,attachmentId,action})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setMessage('Evidence saved against this exact document revision.');setResult('');setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="space-y-3 rounded-xl border bg-white p-4"><h3 className="font-semibold">Approved activity documents and hold points</h3>{error&&<p role="alert" className="text-red-800">{error}</p>}{message&&<p role="status">{message}</p>}<Input aria-label="Filter applicable activity" placeholder="Find activity or inspection…" value={activity} onChange={e=>setActivity(e.target.value)}/>{!documents.length&&!error&&<p className="text-sm">No approved preparation documents linked to this job yet.</p>}{documents.map(doc=><details key={doc.id}><summary className="cursor-pointer py-3">{doc.title} · approved revision {doc.revision}</summary><a className="text-orange-800 underline" href={`/api/preparation/export?id=${encodeURIComponent(doc.id)}&revision=${doc.revision}&format=pdf&shiftId=${encodeURIComponent(shiftId)}`}>Open document</a>{doc.data.rows.filter(r=>(r.question+' '+JSON.stringify(r.fields)).toLowerCase().includes(activity.toLowerCase())).map(row=><div key={row.id} className="my-3 space-y-2 rounded border p-3"><strong>{row.question}</strong><p>{row.fields['Acceptance criteria']||row.answer}</p><p className="text-sm">{row.fields['Hold/witness point']} · {row.fields['Specification reference']}</p><Button variant="outline" disabled={busy} onClick={()=>void record(doc,row.id,'record-check')}>Record inspection</Button>{row.fields['Hold/witness point']&&<Button className="ml-2" disabled={busy} onClick={()=>void record(doc,row.id,'release')}>Authorised release</Button>}</div>)}</details>)}<label className="grid gap-1 text-sm">Inspection result<Textarea value={result} onChange={e=>setResult(e.target.value)}/></label><label className="grid gap-1 text-sm">Supporting photo or file<Input type="file" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const form=new FormData();form.set('file',file);const r=await fetch('/api/delivery/documents',{method:'POST',body:form});const data=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(data.error);setAttachmentId(data.id);setMessage('Evidence uploaded. Select the inspection to record it.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}/></label></section>;
}
