'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';

type Item={id:string;title:string;status:string;document_type:string;revision:number;expiry_date?:string;storage_attachment_id?:string;source_document?:string;source_page?:string;linked_document_id?:string;mandatory?:number};
type Choice={id:string;name:string};
type Data={documents:Item[];requirements:Item[];jobPack:Item[];jobs:Choice[];opportunities:Choice[]};
async function api(url:string,method='GET',body?:unknown){const r=await fetch(url,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(d.error||'Request failed');return d;}
export function IMSWorkspace({jobId:initialJobId='',onNavigate}:{jobId?:string;onNavigate?:(label:string)=>void}){
 const [data,setData]=useState<Data|null>(null),[jobId,setJobId]=useState(initialJobId),[opportunityId,setOpportunityId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 const [title,setTitle]=useState(''),[documentType,setType]=useState('Policy'),[expiry,setExpiry]=useState(''),[file,setFile]=useState<File|null>(null);
 const [requirement,setRequirement]=useState(''),[source,setSource]=useState(''),[page,setPage]=useState(''),[due,setDue]=useState('');
 const [links,setLinks]=useState<Record<string,string>>({});
 useEffect(()=>{let live=true;api(`/api/ims?jobId=${encodeURIComponent(jobId)}&opportunityId=${encodeURIComponent(opportunityId)}`).then(d=>{if(live){setData(d);setError('');}}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[jobId,opportunityId,reload]);
 async function run(task:()=>Promise<unknown>){setBusy(true);setError('');try{await task();setReload(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}
 async function upload(f:File){const form=new FormData();form.set('file',f);const r=await fetch('/api/delivery/documents',{method:'POST',body:form});const d=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(d.error||'Upload failed');return d.id;}
 const transition=(kind:string,item:Item,status:string)=>run(()=>api('/api/ims','PATCH',{kind,id:item.id,status,documentId:links[item.id]||item.linked_document_id}));
 return <section className="space-y-5"><h1 className="text-2xl font-bold">IMS & Compliance</h1>{error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3">{error}</p>}{!data?<p role="status">Loading compliance records…</p>:<>
 <div className="grid gap-3 sm:grid-cols-2"><label>Project<NativeSelect aria-label="IMS project" value={jobId} onChange={e=>setJobId(e.target.value)}><NativeSelectOption value="">Corporate library</NativeSelectOption>{data.jobs.map(j=><NativeSelectOption key={j.id} value={j.id}>{j.name}</NativeSelectOption>)}</NativeSelect></label><label>Tender<NativeSelect aria-label="IMS tender" value={opportunityId} onChange={e=>setOpportunityId(e.target.value)}><NativeSelectOption value="">Select opportunity</NativeSelectOption>{data.opportunities.map(j=><NativeSelectOption key={j.id} value={j.id}>{j.name}</NativeSelectOption>)}</NativeSelect></label></div>
 <section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="text-xl font-semibold">{jobId?'Project and corporate evidence':'Corporate document library'}</h2><div className="grid gap-3 sm:grid-cols-2"><label>Title<Input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Document type<Input value={documentType} onChange={e=>setType(e.target.value)}/></label><label>Expiry date (if applicable)<Input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label>Source file<Input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><Button disabled={busy||!title.trim()||!file} onClick={()=>void run(async()=>{const storageAttachmentId=await upload(file!);await api('/api/ims','POST',{action:'document',title,documentType,expiryDate:expiry,jobId,storageAttachmentId});setTitle('');})}>Save document draft</Button>
 {!data.documents.length&&<p>No evidence uploaded yet.</p>}{data.documents.map(d=><article key={d.id} className="space-y-2 rounded-lg border p-3"><h3 className="font-semibold">{d.title}</h3><p className="text-sm">{d.document_type} · Revision {d.revision} · {d.status}{d.expiry_date?` · Expires ${d.expiry_date}`:''}</p><div className="flex flex-wrap gap-2">{d.storage_attachment_id&&<a className="px-3 py-2 text-orange-800 underline" href={`/api/delivery/documents?id=${encodeURIComponent(d.storage_attachment_id)}`} target="_blank" rel="noreferrer">View source</a>}{['Draft','Rejected'].includes(d.status)&&<Button disabled={busy} variant="outline" onClick={()=>void transition('document',d,'Internal Review')}>Submit review</Button>}{d.status==='Internal Review'&&<><Button disabled={busy} onClick={()=>void transition('document',d,'Approved')}>Approve</Button><Button disabled={busy} variant="outline" onClick={()=>void transition('document',d,'Rejected')}>Reject</Button></>}{d.status==='Approved'&&<Button disabled={busy} variant="outline" onClick={()=>void transition('document',d,'Submitted')}>Record submission</Button>}{d.status==='Submitted'&&<Button disabled={busy} variant="outline" onClick={()=>void transition('document',d,'Accepted')}>Record acceptance</Button>}</div><details><summary>Upload a new revision</summary><p className="my-2 text-sm">The previous source and audit record are retained. The new revision requires approval.</p><label>Replacement file<Input disabled={busy} type="file" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const storageAttachmentId=await upload(f);await api('/api/ims','PUT',{id:d.id,revision:d.revision,storageAttachmentId,reason:'Replacement source uploaded for review'});});}}/></label></details></article>)}</section>
 {opportunityId&&<section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="text-xl font-semibold">Tender requirements</h2><div className="grid gap-3 sm:grid-cols-2"><label>Requirement<Input value={requirement} onChange={e=>setRequirement(e.target.value)}/></label><label>Source document<Input value={source} onChange={e=>setSource(e.target.value)}/></label><label>Source page<Input value={page} onChange={e=>setPage(e.target.value)}/></label><label>Due date<Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div><Button disabled={busy||!requirement.trim()} onClick={()=>void run(async()=>{await api('/api/ims','POST',{action:'requirement',opportunityId,title:requirement,sourceDocument:source,sourcePage:page,dueDate:due});setRequirement('');})}>Add mandatory requirement</Button>{data.requirements.map(r=><article key={r.id} className="rounded border p-3"><p>{r.title} · {r.status}</p><p className="text-sm">{r.source_document} · {r.source_page}</p></article>)}</section>}
 {jobId&&<section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="text-xl font-semibold">Project readiness requirements</h2>{!data.jobPack.length&&<Button disabled={busy} onClick={()=>void run(()=>api('/api/ims','POST',{action:'job-pack',jobId}))}>Create IMS pack for existing job</Button>}{data.jobPack.map(i=><article key={i.id} className="space-y-2 rounded border p-3"><p className="font-semibold">{i.title} · {i.status}</p><NativeSelect aria-label={`Evidence for ${i.title}`} value={links[i.id]??i.linked_document_id??''} onChange={e=>setLinks({...links,[i.id]:e.target.value})}><NativeSelectOption value="">Select approved evidence</NativeSelectOption>{data.documents.filter(d=>['Approved','Accepted'].includes(d.status)).map(d=><NativeSelectOption key={d.id} value={d.id}>{d.title} · Rev {d.revision}</NativeSelectOption>)}</NativeSelect><Button disabled={busy||!(links[i.id]||i.linked_document_id)} variant="outline" onClick={()=>void transition('job-pack',i,'Approved')}>Verify requirement</Button></article>)}{onNavigate&&<Button variant="outline" onClick={()=>onNavigate('Planning')}>Open shift planning</Button>}</section>}
 </>}</section>;
}
