'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {IMSWorkspace} from '@/components/ims-workspace';
import type {NavLabel} from '@/components/operations-workspace';
type Row={id:string;name:string;status:string;created_at?:string;work_date?:string;amount?:number;metadata?:Record<string,unknown>};
type Data={jobs:Row[];job?:Row;shifts?:Row[];dockets?:Row[];variations?:Row[];claims?:Row[];documents?:Row[];activity?:Row[];blockers?:string[]};
export function JobHub({onNavigate}:{onNavigate:(label:NavLabel)=>void}){
 const [jobId,setJobId]=useState(''),[tab,setTab]=useState('Overview'),[data,setData]=useState<Data|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;fetch('/api/job-hub?jobId='+encodeURIComponent(jobId)).then(async r=>{const d=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(d.error||'Job could not be loaded');if(live){setData(d);setError('');}}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[jobId]);
 const tabs=['Overview','Tender baseline','Programme','Shifts','Resources','Field','Dockets','QA & Safety','Variations','Commercial forecast','Claims','Documents','Activity history'];
 const collections:Record<string,Row[]|undefined>={'Programme':data?.shifts,'Shifts':data?.shifts,'Dockets':data?.dockets,'Variations':data?.variations,'Claims':data?.claims,'Documents':data?.documents,'Activity history':data?.activity};
 const destinations:Partial<Record<string,NavLabel>>={'Programme':'Planning','Shifts':'Planning','Resources':'Resources','Field':'Field','Dockets':'Dockets','Variations':'Commercial','Claims':'Commercial','Commercial forecast':'Commercial'};
 return <section className="space-y-4"><h1 className="text-2xl font-bold">Job Hub</h1>{error&&<p role="alert" className="rounded bg-red-50 p-3">{error}</p>}<NativeSelect aria-label="Job Hub project" value={jobId} onChange={e=>setJobId(e.target.value)}><NativeSelectOption value="">Choose an awarded job</NativeSelectOption>{data?.jobs.map(j=><NativeSelectOption key={j.id} value={j.id}>{j.name}</NativeSelectOption>)}</NativeSelect>{!jobId?<p className="rounded border bg-white p-4">Select a job to view its baseline, IMS requirements and delivery records.</p>:data?.job&&<><h2 className="text-xl font-semibold">{data.job.name}</h2><nav aria-label="Job workspace" className="flex gap-2 overflow-x-auto pb-3">{tabs.map(t=><Button key={t} className="shrink-0" variant={tab===t?'default':'outline'} onClick={()=>setTab(t)}>{t}</Button>)}</nav>{tab==='Overview'&&<div className="space-y-3 rounded-xl border bg-white p-4"><p>Status: {data.job.status}</p><p>Client: {String(data.job.metadata?.client||'Not recorded')}</p><p>Site: {String(data.job.metadata?.site||'Not recorded')}</p><h3 className="font-semibold">Commencement readiness</h3>{data.blockers?.length?<ul className="list-disc pl-5 text-amber-900">{data.blockers.map(x=><li key={x}>{x}</li>)}</ul>:<p>Mandatory IMS evidence is complete. Check shift resources and permits before dispatch.</p>}<Button onClick={()=>setTab('QA & Safety')}>Review IMS pack</Button></div>}{tab==='Tender baseline'&&<div className="rounded-xl border bg-white p-4"><h3 className="font-semibold">Approved estimate baseline</h3><pre className="mt-3 overflow-auto whitespace-pre-wrap text-sm">{JSON.stringify(data.job.metadata?.approvedBudget||{},null,2)}</pre></div>}{tab==='QA & Safety'&&<IMSWorkspace key={jobId} jobId={jobId} onNavigate={label=>onNavigate(label as NavLabel)}/>}{collections[tab]&&<div className="space-y-2">{collections[tab]!.length?collections[tab]!.map(r=><article key={r.id} className="rounded border bg-white p-3"><h3 className="font-medium">{r.name}</h3><p>{r.status} {r.work_date||r.created_at||''}</p></article>):<p>No linked records yet.</p>}</div>}{destinations[tab]&&<Button variant="outline" onClick={()=>onNavigate(destinations[tab]!)}>Open {destinations[tab]} workspace</Button>}</>}</section>;
}
