"use client";
import { useEffect,useEffectEvent, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { CHECKS, SHIFT_STATUSES, assignments, jobDetails, plannedCost, shiftWarnings, type DeliveryRecord, type Meta, type Assignment } from '@/lib/planning';
type Field = [string,string,string?];
const jobFields: Field[] = [['client','Client'],['site','Site'],['clientJobNumber','Client job number'],['po','Purchase order'],['wol','WOL'],['contractValue','Contract value ex GST','number'],['workType','Work type'],['projectManager','Project manager'],['supervisor','Supervisor'],['siteContact','Site contact and phone'],['contacts','Project contacts','textarea'],['location','Site location'],['access','Access instructions','textarea'],['startDate','Programme start','date'],['endDate','Programme finish','date'],['workingStart','Working start','time'],['workingFinish','Working finish','time'],['occupancyStart','Approved occupancy start','time'],['occupancyFinish','Approved occupancy finish','time'],['scope','Scope','textarea'],['specification','Specification','textarea'],['methodology','Methodology','textarea'],['costCodes','Cost codes','textarea'],['risks','Risks','textarea'],['constraints','Constraints','textarea'],['holdPoints','Hold points','textarea'],['permit','Permit / approval references','textarea'],['tmp','TMP reference'],['tgs','TGS reference'],['documents','Documents and drawing links / references','textarea']];
const shiftFields:Field[] = [['date','Shift date','date'],['start','Planned start','time'],['finish','Planned finish','time'],['occupancyStart','Occupancy start','time'],['occupancyFinish','Occupancy finish','time'],['scope','Shift scope','textarea'],['chainage','Chainage'],['location','Location'],['area','Planned area (m²)','number'],['tonnes','Planned tonnes','number'],['mix','Asphalt mix'],['supervisor','Supervisor'],['siteContact','Client / site contact'],['po','Purchase order'],['permit','Permits and approvals'],['tmp','TMP'],['tgs','TGS'],['documents','Drawings and document links / references','textarea'],['weather','Weather forecast and source','textarea'],['preStart','Pre-start requirements','textarea'],['instructions','Notes and instructions','textarea'],['materialCost','Planned materials cost','number'],['otherCost','Other planned costs','number']];
const categories = ['workers','crews','plant','suppliers','subcontractors'];
const roles = ['Worker','Crew','Supervisor','Paver','Roller','Profiler','Truck','Other plant','Traffic crew','Traffic vehicle','PTCD','VMS','TMA','AWV','Supplier','Subcontractor'];
const money=(v:unknown)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(v)||0);
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Australia/Sydney'});
function addDays(date:string,n:number) { const d=new Date(date+'T12:00:00Z'); d.setUTCDate(d.getUTCDate()+n); return d.toISOString().slice(0,10); }
export function JobsPlanning({page}:{page:'Jobs'|'Planning'}) {
  const [data,setData]=useState<Record<string,DeliveryRecord[]>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [editor,setEditor]=useState<DeliveryRecord|null>(null); const [kind,setKind]=useState<'jobs'|'shifts'>('jobs'); const [saving,setSaving]=useState(false);
  const [view,setView]=useState('Day'); const [date,setDate]=useState(today); const [jobFilter,setJobFilter]=useState(''); const [search,setSearch]=useState(''); const [resourceCategory,setResourceCategory]=useState('workers');
  const [uploading,setUploading]=useState(false);
  async function upload(file:File) {setUploading(true);setError('');try{const form=new FormData();form.set('file',file);const response=await fetch('/api/delivery/documents',{method:'POST',body:form});const result=await response.json() as {id:string;name:string;url:string;error?:string};if(!response.ok)throw new Error(result.error);setEditor(old=>old?{...old,metadata:{...old.metadata,files:[...((old.metadata.files||[]) as unknown[]),result]}}:old);}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setUploading(false);}}
  async function reload() { const response=await fetch('/api/delivery',{cache:'no-store'}); const body=await response.json() as Record<string,DeliveryRecord[]> & {error?:string}; if(!response.ok) throw new Error(body.error||'Unable to load'); setData(body); }
  useEffect(()=>{const abort=new AbortController();fetch('/api/delivery',{cache:'no-store',signal:abort.signal}).then(async r=>{const b=await r.json() as Record<string,DeliveryRecord[]> & {error?:string};if(!r.ok)throw new Error(b.error||'Unable to load');setData(b);}).catch(e=>{if(!abort.signal.aborted)setError(String(e));}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[]);
  const jobs=data.jobs||[]; const shifts=data.shifts||[]; const resources=categories.flatMap(c=>data[c]||[]);
  function edit(record:DeliveryRecord,type:'jobs'|'shifts') { setError(''); setKind(type);setEditor(structuredClone({...record,metadata:type==='jobs'?jobDetails(record):record.metadata})); }
  function newShift(job?:DeliveryRecord) { const j=job?jobDetails(job):{}; const snapshot=(j.estimateSnapshot||{}) as Meta; edit({id:'',name:job?`${job.name} shift`:'New shift',status:'Draft',metadata:{jobId:job?.id||'',date,start:j.workingStart||'07:00',finish:j.workingFinish||'17:00',classification:'Day',scope:j.scope||'',location:j.location||j.site||'',mix:snapshot.asphaltMix||'AC14',supervisor:j.supervisor||'',siteContact:j.siteContact||'',po:j.po||'',permit:j.permit||'',tmp:j.tmp||'',tgs:j.tgs||'',occupancyStart:j.occupancyStart||'',occupancyFinish:j.occupancyFinish||'',assignments:[],checks:{}}},'shifts'); }
  const warnings=editor&&kind==='shifts'?shiftWarnings(editor,jobs,shifts,resources):[];
  const patch=(key:string,value:unknown)=>setEditor(old=>old?{...old,metadata:{...old.metadata,[key]:value}}:old);
  async function save(event:React.FormEvent) {event.preventDefault();if(!editor)return;setSaving(true);setError('');try{const response=await fetch('/api/delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,record:editor})}); const body=await response.json() as {error?:string}; if(!response.ok)throw new Error(body.error); await reload();setEditor(null);}catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setSaving(false);}}
  function updateAssignment(index:number,update:Partial<Assignment>) { if(editor)patch('assignments',assignments(editor).map((a,i)=>i===index?{...a,...update}:a)); }
  const startOfWeek=addDays(date,-((new Date(date+'T12:00:00Z').getUTCDay()+6)%7)); const days=view==='Week'?Array.from({length:7},(_,i)=>addDays(startOfWeek,i)):[date];
  const visible=shifts.filter(s=>(!jobFilter||s.metadata.jobId===jobFilter)&&(!search||s.name.toLowerCase().includes(search.toLowerCase()))&&(view==='List'||days.includes(String(s.metadata.date)))).sort((a,b)=>`${a.metadata.date} ${a.metadata.start}`.localeCompare(`${b.metadata.date} ${b.metadata.start}`));
  const card=(s:DeliveryRecord)=>{const warnings=shiftWarnings(s,jobs,shifts,resources);return <button key={s.id} className="w-full rounded-lg border-l-4 border-l-orange-500 bg-white p-3 text-left shadow-sm hover:bg-orange-50" onClick={()=>edit(s,'shifts')}><p className="font-semibold">{s.name}</p><p className="text-sm">{String(s.metadata.date||'Undated')} · {String(s.metadata.start||'')}–{String(s.metadata.finish||'')} · {String(s.metadata.classification||'Day')}</p><p className="text-sm text-slate-600">{jobs.find(j=>j.id===s.metadata.jobId)?.name||String(s.metadata.job||'Unlinked job')}</p><p className="text-sm">{String(s.metadata.tonnes||0)} t · {assignments(s).length} resources · {s.status}</p><p className="mt-1 text-sm text-amber-800">{warnings.length?`${warnings.length} readiness warnings`:'No allocation warnings'}</p></button>;};
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">{page==='Jobs'?'Jobs & approved budgets':'Shift planner & dispatch'}</h2><p className="text-sm text-slate-500">{page==='Jobs'?'Set up awarded work and plan delivery.':'Sydney local time · overnight shifts finish the following day.'}</p></div><Button onClick={()=>page==='Jobs'?edit({id:'',name:'',status:'Planning',metadata:{}},'jobs'):newShift(jobs.find(j=>j.id===jobFilter))}>{page==='Jobs'?'New job':'New shift'}</Button></div>
    {error&&!editor&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3">{error}<Button variant="outline" className="ml-3" onClick={()=>reload().then(()=>setError('')).catch(e=>setError(e.message))}>Retry</Button></p>}
    {loading?<p>Loading saved jobs and shifts…</p>:page==='Jobs'?<div className="grid gap-4 lg:grid-cols-2">{!jobs.length&&<p className="rounded border bg-white p-6">No jobs yet. Award an estimate or create a job.</p>}{jobs.map(job=>{const m=jobDetails(job);const b=(m.approvedBudget||{}) as Meta;return <article key={job.id} className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><h3 className="font-bold">{job.name}</h3><span>{job.status}</span></div><p className="text-sm text-slate-600">{String(m.client||'Client not set')} · {String(m.site||'Site not set')}</p><div className="my-4 grid grid-cols-2 gap-3"><div><p className="text-sm text-slate-500">Contract ex GST</p><strong>{money(m.contractValue)}</strong></div><div><p className="text-sm text-slate-500">Approved cost baseline</p><strong>{m.approvedBudget?money(b.totalCost):'Not awarded'}</strong></div></div><p className="mb-3 text-sm">{shifts.filter(s=>s.metadata.jobId===job.id).length} shifts · PM {String(m.projectManager||'Unassigned')}</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>edit(job,'jobs')}>Open job</Button><Button onClick={()=>newShift(job)}>Plan shift</Button></div></article>;})}</div>:<><div className="flex flex-wrap gap-2 rounded-xl border bg-white p-3">{['Day','Week','List'].map(v=><Button key={v} variant={view===v?'default':'outline'} onClick={()=>setView(v)}>{v}</Button>)}<Button aria-label="Previous period" variant="outline" onClick={()=>setDate(addDays(date,view==='Week'?-7:-1))}>←</Button><Input aria-label="Planner date" className="w-40" type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/><Button aria-label="Next period" variant="outline" onClick={()=>setDate(addDays(date,view==='Week'?7:1))}>→</Button><NativeSelect aria-label="Filter job" value={jobFilter} onChange={e=>setJobFilter(e.target.value)}><NativeSelectOption value="">All jobs</NativeSelectOption>{jobs.map(j=><NativeSelectOption key={j.id} value={j.id}>{j.name}</NativeSelectOption>)}</NativeSelect><Input className="w-48" aria-label="Search shifts" placeholder="Search shifts" value={search} onChange={e=>setSearch(e.target.value)}/></div>{view==='List'?<div className="grid gap-3 lg:grid-cols-3">{visible.map(card)}{!visible.length&&<p>No shifts found. Create a shift to dispatch work.</p>}</div>:<div className="overflow-x-auto"><div className={view==='Week'?'grid min-w-[1100px] grid-cols-7 gap-2':'space-y-3'}>{days.map(d=><section key={d} className="min-h-60 rounded-lg bg-slate-200/60 p-2"><h3 className="mb-3 font-semibold">{new Date(d+'T12:00:00Z').toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'})}</h3><div className="space-y-2">{visible.filter(s=>s.metadata.date===d).map(card)}</div>{!visible.some(s=>s.metadata.date===d)&&<p className="text-sm text-slate-500">No shifts</p>}</section>)}</div></div>}</>}
    <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!saving)setEditor(null);}}><DialogContent className="max-h-[94dvh] overflow-y-auto sm:max-w-5xl"><DialogTitle>{kind==='jobs'?'Job setup':'Shift details'}{editor?.id?'':' · New'}</DialogTitle><DialogDescription>{kind==='jobs'?'Approved estimate values are retained as a locked baseline.':'Save a draft at any time. Readiness checks must pass before dispatch.'}</DialogDescription>{editor&&<form onSubmit={save} className="space-y-5">{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Name<Input required value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><label className="text-sm font-medium">Status<NativeSelect value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value})}>{[...new Set([editor.status,...(kind==='jobs'?['Planning','Active','On hold','Complete','Closed']:SHIFT_STATUSES)])].map(s=><NativeSelectOption key={s} value={s}>{s}</NativeSelectOption>)}</NativeSelect></label>{kind==='shifts'&&<><label className="text-sm font-medium">Job<NativeSelect required value={String(editor.metadata.jobId||'')} onChange={e=>patch('jobId',e.target.value)}><NativeSelectOption value="">Select job</NativeSelectOption>{jobs.map(j=><NativeSelectOption key={j.id} value={j.id}>{j.name}</NativeSelectOption>)}</NativeSelect></label><label className="text-sm font-medium">Classification<NativeSelect value={String(editor.metadata.classification||'Day')} onChange={e=>patch('classification',e.target.value)}>{['Day','Night','Weekend'].map(v=><NativeSelectOption key={v} value={v}>{v}</NativeSelectOption>)}</NativeSelect></label></>}{(kind==='jobs'?jobFields:shiftFields).map(([key,label,type])=><label key={key} className={`text-sm font-medium ${type==='textarea'?'sm:col-span-2':''}`}>{label}{type==='textarea'?<Textarea rows={2} value={String(editor.metadata[key]||'')} onChange={e=>patch(key,e.target.value)}/>:<Input required={kind==='shifts'&&['date','start','finish'].includes(key)} type={type||'text'} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={String(editor.metadata[key]??'')} onChange={e=>patch(key,type==='number'?Number(e.target.value):e.target.value)}/>}</label>)}</div>
    {kind==='jobs'&&<section className="rounded-lg bg-slate-100 p-4"><h3 className="font-bold">Approved estimate baseline</h3>{editor.metadata.approvedBudget?<><p>Cost {money((editor.metadata.approvedBudget as Meta).totalCost)} · {(editor.metadata.approvedBudget as Meta).totalTonnes as number} t · {(editor.metadata.approvedBudget as Meta).estimatedShifts as number} shifts</p><p className="break-all text-sm">Estimate {String(editor.metadata.sourceEstimateId)} · Revision {String(editor.metadata.sourceRevisionId)}</p></>:<p>No approved estimate linked. Award an estimate to create a budget-backed job.</p>}</section>}
    {kind==='shifts'&&<><section className="space-y-3 rounded-lg border p-3"><h3 className="font-bold">Resource assignments</h3><NativeSelect aria-label="Resource category" value={resourceCategory} onChange={e=>setResourceCategory(e.target.value)}>{categories.map(c=><NativeSelectOption key={c} value={c}>{c}</NativeSelectOption>)}</NativeSelect><div className="flex max-h-40 flex-wrap gap-2 overflow-y-auto">{(data[resourceCategory]||[]).map(r=><Button key={r.id} type="button" variant="outline" disabled={assignments(editor).some(a=>a.resourceId===r.id)} onClick={()=>patch('assignments',[...assignments(editor),{resourceId:r.id,category:resourceCategory,name:r.name,role:resourceCategory==='plant'?String(r.metadata.type||'Other plant'):resourceCategory==='workers'?'Worker':resourceCategory==='crews'?'Crew':resourceCategory==='suppliers'?'Supplier':'Subcontractor',hours:8,rate:Number(r.metadata.hourlyRate||r.metadata.rate||0),payload:Number(r.metadata.payload||0),trips:0}])}>+ {r.name}</Button>)}{!(data[resourceCategory]||[]).length&&<p className="text-sm">Add {resourceCategory} in Resources first, then reopen Planning.</p>}</div>{assignments(editor).map((a,i)=><div key={a.resourceId} className="grid gap-2 rounded border bg-slate-50 p-3 sm:grid-cols-3"><strong className="sm:col-span-2">{a.name}</strong><Button type="button" variant="outline" onClick={()=>patch('assignments',assignments(editor).filter((_,n)=>n!==i))}>Remove</Button><label className="text-sm">Role<NativeSelect value={a.role} onChange={e=>updateAssignment(i,{role:e.target.value})}>{[...new Set([a.role,...roles])].map(r=><NativeSelectOption key={r} value={r}>{r}</NativeSelectOption>)}</NativeSelect></label>{(['hours','rate','payload','trips'] as const).map(key=><label key={key} className="text-sm">{key==='payload'?'Truck payload (t)':key==='rate'?'Rate per hour':key}<Input type="number" min="0" step="any" value={a[key]} onChange={e=>updateAssignment(i,{[key]:Number(e.target.value)})}/></label>)}{a.role==='Truck'&&<p className="text-sm">Trips for shift tonnage: {a.payload>0?Math.ceil(Number(editor.metadata.tonnes||0)/a.payload):'Enter payload'}</p>}</div>)}<strong className="block">Planned shift cost: {money(plannedCost(editor))}</strong></section><section className="rounded-lg border p-4"><h3 className="mb-3 font-bold">Shift readiness</h3><div className="grid gap-3 sm:grid-cols-2">{CHECKS.map(c=><label className="flex items-center gap-2 text-sm" key={c}><Checkbox checked={Boolean((editor.metadata.checks as Record<string,boolean>||{})[c])} onCheckedChange={v=>patch('checks',{...(editor.metadata.checks as Meta||{}),[c]:v===true})}/>{c}</label>)}</div><div className="mt-4 space-y-1 text-sm text-amber-900">{warnings.map(w=><p key={w}>⚠ {w}</p>)}{!warnings.length&&<p className="text-green-800">Resource and job checks passed.</p>}</div></section></>}
    <section className="rounded border p-3"><h3 className="font-bold">Attached documents</h3><label className="block text-sm">Upload drawing, TMP, TGS or permit (up to 20 MB)<Input type="file" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/></label>{uploading&&<p>Uploading…</p>}{((editor.metadata.files||[]) as {id:string;name:string;url:string}[]).map(f=><a className="mt-2 block break-all text-sm text-blue-700 underline" key={f.id} href={`/api/delivery/documents?id=${encodeURIComponent(f.id)}`}>{f.name}</a>)}<p className="mt-2 text-sm text-slate-500">Save the job or shift to retain these document links.</p></section>
    <div className="sticky bottom-0 flex justify-end gap-2 border-t bg-white py-3"><Button type="button" variant="outline" disabled={saving||uploading} onClick={()=>setEditor(null)}>Cancel</Button><Button type="submit" disabled={saving||uploading}>{saving?'Saving…':'Save '+(kind==='jobs'?'job':'shift')}</Button></div></form>}</DialogContent></Dialog>
  </div>;
}
