'use client';
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { blankData, blankRow, DOCUMENT_TYPES, PLAN_SECTIONS, TABLE_FIELDS, suggestedAnswers, type PreparationData, type PreparationRecord, type PreparationRow } from '@/lib/preparation';
import { readTender } from '@/lib/tender-reader';
type Option={id:string;name:string};
type Payload={records:PreparationRecord[];jobs:Option[];opportunities:Option[];users:Option[];actor:{userId:string;role:string};issues:Record<string,string[]>;entitlements:Record<string,boolean>};
const KINDS:Record<string,string>={company:'Company information',answer:'Approved answers',template:'Templates',submission:'Tender / VIPQ responses',plan:'Project plans',risk:'Risk registers',itp:'ITPs',action:'Actions & clarifications','project-pack':'Pre-commencement',allowance:'Draft allowances',settings:'Organisation configuration'};
function latest(records:PreparationRecord[]){return records.filter(r=>!records.some(n=>n.id===r.id&&n.revision>r.revision));}
function Select({label,value,onChange,options,empty='Select…'}:{label:string;value:string;onChange:(v:string)=>void;options:Option[];empty?:string}){return <label className="grid gap-1 text-sm">{label}<NativeSelect value={value} onChange={e=>onChange(e.target.value)}><NativeSelectOption value="">{empty}</NativeSelectOption>{options.map(o=><NativeSelectOption key={o.id} value={o.id}>{o.name}</NativeSelectOption>)}</NativeSelect></label>;}
export function PreparationWorkspace(){
 const [payload,setPayload]=useState<Payload|null>(null),[selected,setSelected]=useState<PreparationRecord|null>(null),[category,setCategory]=useState('submission'),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[modal,setModal]=useState(''),[detail,setDetail]=useState({title:'',jobId:'',reference:'',date:'',method:'',comment:'',rowId:'',client:'',site:'',scope:''});
 const load=useCallback(async()=>{const r=await fetch('/api/preparation');const data=await r.json() as Payload & {error?:string};if(!r.ok)throw new Error(data.error);setPayload(data);return data as Payload;},[]);
 useEffect(()=>{let live=true;fetch('/api/preparation').then(async r=>{const data=await r.json() as Payload & {error?:string};if(!r.ok)throw new Error(data.error);return data;}).then(data=>{if(live)setPayload(data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const change=(patch:Partial<PreparationRecord>)=>{setSelected(s=>s?{...s,...patch}:s);setDirty(true);};
 const dataChange=(patch:Partial<PreparationData>)=>{if(selected)change({data:{...selected.data,...patch}});};
 const rowChange=(id:string,patch:Partial<PreparationRow>)=>{if(selected)dataChange({rows:selected.data.rows.map(r=>r.id===id?{...r,...patch}:r)});};
 async function execute(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');setNotice('');try{
  const r=await fetch('/api/preparation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selected,id:selected?.revision?selected.id:undefined,jobId:selected?.job_id,opportunityId:selected?.opportunity_id,action,...extra})});const result=await r.json() as {record?:PreparationRecord;error?:string};if(!r.ok)throw new Error(result.error);if(result.record){setSelected(result.record);setCategory(result.record.kind);setDirty(false);}await load();setModal('');setNotice(action==='save'?'Saved. Refresh will retain this revision.':action==='extract'?'Draft questions extracted. Check each against its original.':'Action recorded.');return result.record as PreparationRecord|undefined;
 }catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}}
 function choose(record:PreparationRecord){if(dirty){setError('Save your changes before opening another record.');return;}setSelected(structuredClone(record));setError('');setNotice('');}
 function create(){if(dirty){setError('Save the current draft first.');return;}const data=blankData();if(category==='plan'||category==='template')data.sections=PLAN_SECTIONS.map(title=>({title,text:title==='Project overview'?'Project: {{project}}\nClient: {{client}}\nLocation: {{location}}':title==='Scope and commitments'?'{{scope}}':title==='Programme and work hours'?'{{programme}}':title==='Roles and responsibilities'?'{{personnel}}':title==='Resources and subcontractors'?'{{resources}}':'',source:''}));data.owner=payload?.actor.userId||'';if(['company','answer'].includes(category))data.sections=[{title:category==='company'?'Company identity and verified information':'Purpose and scope',text:'',source:''}];setSelected({id:'',revision:0,kind:category as PreparationRecord['kind'],title:'',status:'Draft',organisation_id:'',job_id:null,opportunity_id:null,data,actor_id:'',reason:'',created_at:new Date().toISOString()});setDirty(true);setNotice('');}
 async function upload(file:File,extract=false){if(!selected)return;if(dirty||!selected.revision){setError('Save this draft before uploading.');return;}setBusy(true);setError('');try{const form=new FormData();form.set('file',file);const response=await fetch('/api/delivery/documents',{method:'POST',body:form});const attachment=await response.json() as {id:string;error?:string};if(!response.ok)throw new Error(attachment.error);
 if(extract){const pages:PreparationData['sourcePages']=[];await readTender(file,async page=>{pages.push({fileId:attachment.id,ref:page.ref,text:page.text,method:page.method,confidence:page.confidence});},setNotice);await execute('extract',{pages});}
 else{dataChange({attachments:[...selected.data.attachments,attachment.id]});setNotice('Original uploaded. Save to link it to this revision.');}
 }catch(e){setError(e instanceof Error?e.message:'Upload failed. Original extraction can be retried.');}finally{setBusy(false);}}
 async function download(format:string){if(!selected?.revision||dirty){setError('Save before exporting.');return;}setBusy(true);try{const r=await fetch(`/api/preparation/export?id=${encodeURIComponent(selected.id)}&revision=${selected.revision}&format=${format}`);if(!r.ok)throw new Error((await r.json() as {error:string}).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`${selected.title.replace(/[^a-zA-Z0-9_-]/g,'_')}-r${selected.revision}.${format}`;a.click();URL.revokeObjectURL(url);setNotice('Export downloaded. Submission status has not changed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const records=latest(payload?.records||[]),evidence=records.filter(r=>['Approved','Accepted','Submitted'].includes(r.status)&&['company','answer','plan','template','risk','itp'].includes(r.kind));const canEdit=!!payload&&!['read-only','field worker','supervisor','accounts'].includes(payload.actor.role);const canApprove=!!payload&&['owner/admin','admin','estimator/commercial manager','commercial manager','ims/qa/safety lead','project manager'].includes(payload.actor.role);const list=records.filter(r=>r.kind===category&&r.title.toLowerCase().includes(search.toLowerCase()));const history=payload?.records.filter(r=>r.id===selected?.id).sort((a,b)=>b.revision-a.revision)||[];
 const locked=selected?.status==='Submitted';const blockers=selected?.revision?payload?.issues[selected.id]||[]:[];
 return <div className="space-y-4 text-base">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Contract preparation</h1><p className="text-sm text-slate-600">Prepare responses, plans and commencement approvals.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>{setModal('create-project');setDetail(d=>({...d,title:''}));}} disabled={!canEdit||busy}>Create project</Button><Button onClick={create} disabled={!canEdit||busy}>New {category==='submission'?'response':category==='project-pack'?'pack':'record'}</Button></div></div>
 <p className="rounded border bg-white p-3 text-sm">PDF, image, DOCX and spreadsheet text extraction is available. AI drafting is not configured. DOCX page numbers are unavailable; section references are retained. Qualified reviewers must confirm plans, criteria and specialist designs.</p>
 {error&&<div role="alert" className="whitespace-pre-wrap rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}<Button variant="outline" className="ml-3" onClick={()=>void load().catch(e=>setError(e.message))}>Retry loading</Button></div>}{notice&&<p role="status" className="rounded bg-green-50 p-3 text-green-900">{notice}</p>}
 <div className="flex gap-2 overflow-x-auto pb-2" aria-label="Preparation work areas">{Object.entries(KINDS).filter(([k])=>k!=='settings'||['owner/admin','admin'].includes(payload?.actor.role||'')).filter(([k])=>payload?.entitlements[k==='submission'||k==='answer'?'tender':'ims']!==false).map(([k,label])=><Button variant={category===k?'default':'outline'} key={k} onClick={()=>{if(dirty){setError('Save the current draft before changing work areas.');return;}setCategory(k);setSelected(null);}}>{label}</Button>)}</div>
 {!payload&&!error?<p role="status">Loading preparation records…</p>:<div className="grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)]"><aside className="space-y-2"><Input aria-label="Search preparation records" placeholder="Find a record…" value={search} onChange={e=>setSearch(e.target.value)}/>{!list.length&&<p className="p-3 text-sm text-slate-600">No {KINDS[category]?.toLowerCase()} yet. Create a record to begin.</p>}{list.map(r=><button key={r.id} onClick={()=>choose(r)} className={`block w-full rounded border p-3 text-left ${selected?.id===r.id?'border-orange-600 bg-orange-50':'bg-white'}`}><span className="block font-medium">{r.title}</span><span className="text-sm text-slate-600">{r.status} · rev {r.revision}</span>{(payload?.issues[r.id]?.length||0)>0&&<span className="block text-sm text-amber-800">{payload?.issues[r.id].length} outstanding checks</span>}</button>)}</aside>
 {!selected?<div className="rounded border bg-white p-6 text-slate-600">Choose a record or start a draft. Approved answers and templates can be reused across projects.</div>:<section className="min-w-0 space-y-4 rounded border bg-white p-4 sm:p-6">
 <div className="flex flex-wrap items-center justify-between gap-3"><span className="font-semibold">{selected.status} · revision {selected.revision||'unsaved'} {dirty?'· unsaved changes':''}</span><Button onClick={()=>void execute('save')} disabled={!canEdit||locked||busy||!dirty}>Save draft</Button></div>
 <fieldset disabled={!canEdit||locked||busy} className="grid min-w-0 gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">Title<Input value={selected.title} onChange={e=>change({title:e.target.value})}/></label><Select label="Owner" value={selected.data.owner} onChange={v=>dataChange({owner:v})} options={payload?.users||[]}/><Select label="Project (optional for tenders)" value={selected.job_id||''} onChange={v=>change({job_id:v||null})} options={payload?.jobs||[]}/><Select label="Opportunity (optional)" value={selected.opportunity_id||''} onChange={v=>change({opportunity_id:v||null})} options={payload?.opportunities||[]}/><label className="grid gap-1 text-sm">Review date<Input type="date" value={selected.data.reviewDate} onChange={e=>dataChange({reviewDate:e.target.value})}/></label><label className="grid gap-1 text-sm">Evidence expiry<Input type="date" value={selected.data.expiryDate} onChange={e=>dataChange({expiryDate:e.target.value})}/></label>
 {['plan','template'].includes(selected.kind)&&<Select label="Document type" value={selected.data.category} onChange={v=>dataChange({category:v})} options={DOCUMENT_TYPES.map(name=>({id:name,name}))}/>}</fieldset>
 {selected.kind==='plan'&&<Select label="Start from an approved template" value="" onChange={v=>{const t=evidence.find(r=>r.id===v);if(t){const job=payload?.jobs.find(j=>j.id===selected.job_id);dataChange({...t.data,owner:selected.data.owner,origin:{id:t.id,revision:t.revision},sections:t.data.sections.map(s=>({...s,text:s.text.replaceAll('{{project}}',job?.name||'{{project}}'),source:`${t.title} revision ${t.revision}`}))});}}} options={evidence.filter(r=>r.kind==='template').map(r=>({id:r.id,name:`${r.title} · rev ${r.revision}`}))}/>}
 <div className="flex flex-wrap gap-3"><label className="grid gap-1 text-sm">{selected.kind==='submission'?'Upload questionnaire and extract draft questions':'Attach supporting original'}<Input disabled={busy||locked||!canEdit} type="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx,.csv" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,selected.kind==='submission');e.target.value='';}}/></label>{selected.data.attachments.map(id=><a key={id} href={`/api/delivery/documents?id=${encodeURIComponent(id)}`} className="self-end text-sm text-orange-800 underline">Open original {id.slice(0,8)}</a>)}</div>
 {selected.kind==='settings'&&<div className="space-y-2"><h2 className="font-semibold">Risk matrix</h2><p className="text-sm">Define your organisation’s likelihood and consequence combinations. Ratings are applied only from the approved configuration revision.</p>{Object.entries(selected.data.matrix).map(([key,rating],i)=><div className="grid gap-2 sm:grid-cols-3" key={i}><Input aria-label="Likelihood and consequence separated by |" value={key} onChange={e=>{const entries=Object.entries(selected.data.matrix);entries[i]=[e.target.value,rating];dataChange({matrix:Object.fromEntries(entries)});}}/><Input aria-label="Risk rating" value={rating} onChange={e=>dataChange({matrix:{...selected.data.matrix,[key]:e.target.value}})}/></div>)}<Button variant="outline" onClick={()=>dataChange({matrix:{...selected.data.matrix,['Likelihood '+(Object.keys(selected.data.matrix).length+1)+'|Consequence']:''}})}>Add matrix combination</Button></div>}
 {selected.kind==='allowance'&&<Button disabled={dirty||busy} onClick={()=>void execute('apply-allowance',{confirm:true})}>Confirm quantity and rate; add to draft estimate</Button>}
 {selected.kind==='plan'&&<Button variant="outline" disabled={dirty||busy||!selected.job_id} onClick={()=>void execute('populate-project')}>Populate from saved project information</Button>}
 <div className="space-y-4">{selected.data.sections.map((s,index)=><fieldset disabled={!canEdit||locked||busy} key={index} className="space-y-2 border-l-4 border-orange-500 pl-3"><Input aria-label={`Section ${index+1} heading`} value={s.title} onChange={e=>dataChange({sections:selected.data.sections.map((x,i)=>i===index?{...x,title:e.target.value}:x)})}/><Textarea aria-label={s.title||`Section ${index+1} content`} rows={7} value={s.text} onChange={e=>dataChange({sections:selected.data.sections.map((x,i)=>i===index?{...x,text:e.target.value}:x)})}/><Input aria-label="Section information source" placeholder="Information source / reference" value={s.source} onChange={e=>dataChange({sections:selected.data.sections.map((x,i)=>i===index?{...x,source:e.target.value}:x)})}/></fieldset>)}</div>
 <Button variant="outline" disabled={!canEdit||locked||busy} onClick={()=>dataChange({sections:[...selected.data.sections,{title:'New section',text:'',source:''}]})}>Add editable section</Button>
 <div className="space-y-4">{selected.data.rows.map((r,index)=><article key={r.id} className="min-w-0 space-y-3 rounded border bg-slate-50 p-3 sm:p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{index+1}. {r.status}{r.notApplicable?' · Not applicable':''}</strong>{r.sourceId&&<a className="text-sm text-orange-800 underline" target="_blank" rel="noreferrer" href={`/api/delivery/documents?id=${encodeURIComponent(r.sourceId)}`}>Source: {r.sourceRef}</a>}</div>
 <fieldset disabled={!canEdit||locked||busy} className="space-y-3"><label className="grid gap-1 text-sm">Question / requirement<Textarea rows={2} value={r.question} onChange={e=>rowChange(r.id,{question:e.target.value})}/></label><label className="grid gap-1 text-sm">Proposed answer / commitment<Textarea rows={4} value={r.answer} onChange={e=>rowChange(r.id,{answer:e.target.value})}/></label>
 <div className="grid gap-3 sm:grid-cols-2">{(TABLE_FIELDS[selected.kind]||[]).map(field=><label key={field} className="grid gap-1 text-sm">{field}<Textarea rows={2} value={r.fields[field]||''} onChange={e=>rowChange(r.id,{fields:{...r.fields,[field]:e.target.value}})}/></label>)}<Select label="Assigned owner" value={r.owner} onChange={v=>rowChange(r.id,{owner:v})} options={payload?.users||[]}/><label className="grid gap-1 text-sm">Due date<Input type="date" value={r.due} onChange={e=>rowChange(r.id,{due:e.target.value})}/></label><Select label="Applies at" value={r.stage} onChange={v=>rowChange(r.id,{stage:v as PreparationRow['stage']})} options={['Tender','Pre-commencement'].map(name=>({id:name,name}))}/><label className="grid gap-1 text-sm">Word limit (0 = none stated)<Input type="number" min={0} value={r.wordLimit} onChange={e=>rowChange(r.id,{wordLimit:Number(e.target.value)})}/></label><label className="grid gap-1 text-sm">Required format<Input value={r.format} onChange={e=>rowChange(r.id,{format:e.target.value})}/></label><label className="grid gap-1 text-sm">Evaluation weighting, if stated<Input value={r.weighting} onChange={e=>rowChange(r.id,{weighting:e.target.value})}/></label><label className="grid gap-1 text-sm">Supporting evidence required<Input value={r.fields['Required evidence']||''} onChange={e=>rowChange(r.id,{fields:{...r.fields,'Required evidence':e.target.value}})}/></label><label className="grid gap-1 text-sm">Source page / sheet / section<Input value={r.sourceRef} onChange={e=>rowChange(r.id,{sourceRef:e.target.value})}/></label></div>
 <div className="flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={r.mandatory} onChange={e=>rowChange(r.id,{mandatory:e.target.checked})}/> Mandatory</label><label><input type="checkbox" checked={!r.uncertain} onChange={e=>rowChange(r.id,{uncertain:!e.target.checked})}/> Interpretation checked against source</label><label><input type="checkbox" checked={r.requiresAcceptance} onChange={e=>rowChange(r.id,{requiresAcceptance:e.target.checked})}/> Client acceptance required</label></div>
 <Select label="Link an approved evidence revision" value="" onChange={v=>{const item=evidence.find(e=>e.id===v);if(item&&!r.evidence.some(e=>e.id===item.id&&e.revision===item.revision))rowChange(r.id,{evidence:[...r.evidence,{id:item.id,revision:item.revision}]});}} options={evidence.map(e=>({id:e.id,name:`${e.title} · revision ${e.revision}${e.data.expiryDate?' · expires '+e.data.expiryDate:''}`}))}/>
 {r.evidence.map(ref=><p className="text-sm" key={`${ref.id}:${ref.revision}`}>{payload?.records.find(e=>e.id===ref.id&&e.revision===ref.revision)?.title||ref.id} · evidence revision {ref.revision}</p>)}
 {selected.kind==='submission'&&suggestedAnswers(r.question,evidence).map(a=><Button key={a.id} variant="outline" className="h-auto min-h-11 whitespace-normal text-left" onClick={()=>rowChange(r.id,{answer:a.data.sections.map(s=>s.text).join('\n\n'),evidence:[...r.evidence,{id:a.id,revision:a.revision}]})}>Reuse: {a.title} · approved rev {a.revision}</Button>)}
 <label className="grid gap-1 text-sm">Outstanding action / review comment<Textarea value={r.comment} onChange={e=>rowChange(r.id,{comment:e.target.value})}/></label></fieldset>
 {r.acceptance&&<p className="text-sm">Client acceptance: {r.acceptance.reference} · {r.acceptance.date}</p>}{r.notApplicable&&<p className="text-sm">Not applicable: {r.notApplicable.reason}</p>}
 <div className="flex flex-wrap gap-2"><Button disabled={!canApprove||dirty||busy||locked} onClick={()=>void execute('approve',{rowId:r.id})}>Approve response</Button>{['accept','exception'].map(action=><Button key={action} variant="outline" disabled={!canApprove||dirty||busy||locked} onClick={()=>{setModal(action);setDetail(d=>({...d,rowId:r.id,reference:''}));}}>{action==='accept'?'Record client acceptance':'Not applicable with reason'}</Button>)}{selected.kind==='submission'&&<Button variant="outline" disabled={!canEdit||dirty||busy} onClick={()=>void execute('allowance',{rowId:r.id})}>Create draft allowance</Button>}</div>
 </article>)}</div>
 <Button variant="outline" disabled={!canEdit||locked||busy} onClick={()=>dataChange({rows:[...selected.data.rows,blankRow()]})}>Add {selected.kind==='submission'?'question':'structured row'}</Button>
 <label className="grid gap-1 text-sm">Clarifications, exclusions, departures and review notes<Textarea disabled={!canEdit||locked||busy} rows={4} value={selected.data.notes} onChange={e=>dataChange({notes:e.target.value})}/></label>
 <div className="rounded border border-amber-200 bg-amber-50 p-3"><h2 className="font-semibold">Completeness review</h2>{dirty?<p>Save to re-evaluate the current content.</p>:blockers.length?<ul className="ml-5 list-disc space-y-1 text-sm">{blockers.map((issue,i)=><li key={i}>{issue}</li>)}</ul>:<p className="text-sm">No saved completeness blockers. Internal approval and any required external acceptance are separate actions.</p>}</div>
 <div className="flex flex-wrap gap-2"><Button disabled={!canEdit||dirty||busy||locked} variant="outline" onClick={()=>void execute('review')}>Request internal review</Button><Button disabled={!canApprove||dirty||busy||locked} onClick={()=>void execute('approve')}>Approve revision</Button><Button disabled={!canEdit||dirty||busy||locked} variant="outline" onClick={()=>setModal('changes')}>Request changes</Button><Button disabled={!canEdit||dirty||busy||!selected.revision} variant="outline" onClick={()=>void execute('copy',{title:`${selected.title} — new draft`,jobId:selected.job_id})}>Copy as new draft</Button>{selected.kind==='submission'&&<><Button disabled={!canApprove||dirty||busy||locked} variant="outline" onClick={()=>setModal('submit')}>Record submission</Button><Button disabled={!canApprove||dirty||busy} variant="outline" onClick={()=>{setModal('handover');setDetail(d=>({...d,jobId:selected.job_id||''}));}}>Transfer to project</Button></>}</div>
 <div className="flex flex-wrap gap-2" aria-label="Export saved revision">{['docx','pdf','xlsx','csv','zip'].map(format=><Button key={format} variant="outline" disabled={busy||dirty||!selected.revision} onClick={()=>void download(format)}>{format==='zip'?'Submission pack ZIP':format.toUpperCase()}</Button>)}</div>
 <details><summary className="cursor-pointer py-3 font-medium">Revision history and comparison ({history.length})</summary>{history.map((r,i)=><div key={r.revision} className="space-y-2 border-t py-3"><p className="text-sm">Revision {r.revision} · {r.status} · {r.reason} · {r.created_at} · {r.actor_id}</p><Button variant="outline" onClick={()=>choose(r)} disabled={dirty}>View this revision</Button>{history[i+1]&&<p className="text-sm">Changed sections: {r.data.sections.filter((s,j)=>JSON.stringify(s)!==JSON.stringify(history[i+1].data.sections[j])).map(s=>s.title).join(', ')||'none'}. Changed rows: {r.data.rows.filter(row=>JSON.stringify(row)!==JSON.stringify(history[i+1].data.rows.find(old=>old.id===row.id))).length}.</p>}</div>)}</details>
 </section>}</div>}
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('');}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogTitle>{modal==='create-project'?'Create a standalone project':modal==='submit'?'Record a submission already sent':modal==='handover'?'Create project commencement pack':modal==='changes'?'Request changes':modal==='accept'?'Record client acceptance':'Not applicable decision'}</DialogTitle><DialogDescription>{modal==='submit'?'This records your action. It does not send or lodge the submission.':'This action is recorded in revision and audit history.'}</DialogDescription>
 {modal==='create-project'&&['title','client','site','scope'].map(key=><label key={key} className="grid gap-1 text-sm">{key}<Input value={detail[key as keyof typeof detail]} onChange={e=>setDetail(d=>({...d,[key]:e.target.value}))}/></label>) }
 {modal==='handover'&&<Select label="Awarded or directly created project" value={detail.jobId} onChange={jobId=>setDetail(d=>({...d,jobId}))} options={payload?.jobs||[]}/>}
 {modal==='changes'?<Textarea aria-label="Requested changes" value={detail.comment} onChange={e=>setDetail(d=>({...d,comment:e.target.value}))}/>:['accept','exception','submit'].includes(modal)&&<label className="grid gap-1 text-sm">{modal==='exception'?'Reason':'Reference / evidence of acceptance'}<Textarea value={detail.reference} onChange={e=>setDetail(d=>({...d,reference:e.target.value}))}/></label>}
 {modal==='submit'&&<><Input aria-label="Submission date" type="date" value={detail.date} onChange={e=>setDetail(d=>({...d,date:e.target.value}))}/><Input aria-label="Submission method" placeholder="Portal / email / other" value={detail.method} onChange={e=>setDetail(d=>({...d,method:e.target.value}))}/></>}
 <Button disabled={busy} onClick={()=>void execute(modal,modal==='create-project'?{...detail,id:undefined,revision:undefined}:{jobId:detail.jobId||selected?.job_id,rowId:detail.rowId,reference:detail.reference,date:detail.date,method:detail.method,comment:detail.comment})}>Record action</Button></DialogContent></Dialog>
 </div>;
}
