'use client';
import {useEffect,useState,useCallback} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {toast} from 'sonner';
import {readTender} from '@/lib/tender-reader';
import {tenderLabels,type TenderDoc,type TenderField,type TenderPage} from '@/lib/tender';
type Pack={documents:TenderDoc[];aiStatus:string;changes:{label:string;before:string;after:string;source:string}[]};
export function TenderReviewAssistant({opportunityId,opportunityName}:{opportunityId:string;opportunityName:string}){
 const [pack,setPack]=useState<Pack>({documents:[],aiStatus:'Checking AI configuration…',changes:[]}),[selected,setSelected]=useState(''),[source,setSource]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[addendum,setAddendum]=useState(''),[draft,setDraft]=useState<{estimateId:string;estimateLines?:{description:string;quantity:number;unit:string;source:string;rate:number|null;rateStatus:string;cost:number}[];missingRates?:string[];totals?:Record<string,number>}|null>(null);
 const url=(id:string)=>`/api/tenders?opportunityId=${encodeURIComponent(opportunityId)}&fileId=${encodeURIComponent(id)}`;
 const load=useCallback(async()=>{const r=await fetch(`/api/tenders?opportunityId=${encodeURIComponent(opportunityId)}`,{cache:'no-store'});const p=await r.json() as Pack&{error?:string};if(!r.ok)throw new Error(p.error||'Could not load documents');setPack(p);},[opportunityId]);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
 async function action(documentId:string,action:string,extra:Record<string,unknown>={}){const r=await fetch('/api/tenders/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({opportunityId,documentId,action,...extra})});const p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error||'Could not save processing result');}
 async function read(doc:TenderDoc){setSelected(doc.id);await action(doc.id,'start');try{const r=await fetch(url(doc.id),{cache:'no-store'});if(!r.ok)throw new Error('Original could not be read from storage');const file=new File([await r.blob()],doc.name,{type:doc.type});await readTender(file,async(page:TenderPage,total:number)=>{await action(doc.id,'page',{page,total});setProgress(`${doc.name}: ${page.ref} saved`);await load();},setProgress);await action(doc.id,'finish');}catch(e){const message=e instanceof Error?e.message:'File processing failed';await action(doc.id,'fail',{error:message});setError(`${doc.name}: ${message}`);}await load();}
 async function upload(files:File[]){setBusy(true);setError('');try{for(const file of files){setProgress(`Preserving ${file.name}…`);const form=new FormData();form.set('opportunityId',opportunityId);form.set('file',file);form.set('addendumNumber',addendum);const r=await fetch('/api/tenders',{method:'POST',body:form});const p=await r.json() as {document:TenderDoc;error?:string};if(!r.ok)throw new Error(p.error);await load();await read(p.document);}setProgress('Pack reading complete. Review the source-linked findings.');}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}}
 async function run(doc:TenderDoc,ai=false){setBusy(true);setError('');try{if(ai){setProgress('Server-side AI analysis…');await action(doc.id,'ai');await load();}else await read(doc);}catch(e){setError(e instanceof Error?e.message:'Processing failed');}finally{setBusy(false);setProgress('');}}
 async function review(field:TenderField,status:TenderField['status'],value?:string){if(!doc)return;try{await action(doc.id,'field',{fieldId:field.id,status,value});await load();}catch(e){toast.error(e instanceof Error?e.message:'Could not save field');}}
 async function estimate(){setBusy(true);try{const r=await fetch('/api/tenders/estimate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({opportunityId})});const p=await r.json() as {error?:string;estimateId?:string;estimateLines?:{description:string;quantity:number;unit:string;source:string;rate:number|null;rateStatus:string;cost:number}[];missingRates?:string[];totals?:Record<string,number>};if(!r.ok||!p.estimateId)throw new Error(p.error||'Draft failed');setDraft({estimateId:p.estimateId,estimateLines:p.estimateLines,missingRates:p.missingRates,totals:p.totals});toast.success('Draft saved in Estimates & Quotes. Quantities, missing rates and assumptions require review.');}catch(e){setError(e instanceof Error?e.message:'Draft failed');}finally{setBusy(false);}}
 const doc=pack.documents.find(d=>d.id===selected)||pack.documents[0];const page=doc?.pages.find(p=>p.ref===source)||doc?.pages[0];const all=pack.documents.flatMap(d=>d.fields||[]);const missing=tenderLabels.filter(label=>!all.some(f=>f.label===label&&f.status!=='Rejected'));
 return <section className="space-y-4 rounded-xl border bg-white p-4"><div><h3 className="text-xl font-bold">Tender Review & Estimate Assistant</h3><p className="text-sm text-slate-500">{opportunityName} · {pack.aiStatus}</p><p className="text-sm text-slate-500">Files are read automatically after upload. Scans use local OCR. AI analysis runs only on the server when configured.</p></div><div className="flex flex-wrap items-end gap-3"><label className="text-sm">Addendum number (optional)<Input value={addendum} onChange={e=>setAddendum(e.target.value)} disabled={busy}/></label><label className="text-sm">Upload tender files<input className="block w-full rounded border p-2" type="file" multiple disabled={busy} accept=".pdf,.png,.jpg,.jpeg,.webp,.tif,.tiff,.bmp,.docx,.xlsx,.csv" onChange={e=>{const files=Array.from(e.target.files||[]);e.currentTarget.value='';void upload(files);}}/></label><Button disabled={busy||!all.some(f=>f.status==='Confirmed')} onClick={estimate}>Create draft estimate from confirmed fields</Button></div>{pack.aiStatus==='AI not configured'&&<p className="rounded bg-amber-50 p-3 text-sm">AI not configured. Local OCR and deterministic extraction remain available. A provider can be configured later in the Site’s secure runtime settings; never paste an API key into a tender field.</p>}{progress&&<p role="status" className="rounded bg-blue-50 p-3 text-sm">{progress}</p>}{error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm">{error} Uploaded originals remain available.</p>}
 <div className="space-y-2">{!pack.documents.length&&<p className="rounded border border-dashed p-5 text-slate-500">Upload a tender pack to begin. No tender findings have been generated.</p>}{pack.documents.map(d=><div key={d.id} className={`flex flex-wrap items-center justify-between gap-3 rounded border p-3 ${doc?.id===d.id?'border-orange-400 bg-orange-50':''}`}><button className="text-left" onClick={()=>{setSelected(d.id);setSource('');}}><strong>{d.name}</strong><p className="text-sm text-slate-600">{d.type} · {(d.size/1024).toFixed(1)} KB · {new Date(d.uploadDate).toLocaleDateString('en-AU')} · {d.pageCount??'Unknown'} pages / sheets / sections{d.addendumNumber&&` · Addendum ${d.addendumNumber}`}</p><p className="text-sm">{d.processingStatus} · {d.ocrStatus} · {d.aiStatus}</p>{d.errors.map((e,i)=><p key={i} className="text-sm text-red-700">{e}</p>)}</button><div className="flex flex-wrap gap-2"><a className="rounded border bg-white px-3 py-2 text-sm" href={url(d.id)} target="_blank" rel="noreferrer">Open original</a><Button variant="outline" disabled={busy} onClick={()=>run(d)}>Reprocess file</Button><Button variant="outline" disabled={busy||pack.aiStatus==='AI not configured'||!d.pages.length} onClick={()=>run(d,true)}>Analyse with AI</Button></div></div>)}</div>
 {doc&&<div className="grid gap-4 xl:grid-cols-2"><div className="min-w-0 space-y-3 rounded border p-3"><h4 className="font-semibold">Source viewer — {doc.name}</h4><select aria-label="Source page or sheet" className="w-full rounded border p-2" value={page?.ref||''} onChange={e=>setSource(e.target.value)}>{doc.pages.map(p=><option key={p.ref} value={p.ref}>{p.ref}{p.error?' — failed':''}</option>)}</select>{doc.name.toLowerCase().endsWith('.pdf')?<iframe title="Tender original PDF" className="h-[480px] w-full border" src={`${url(doc.id)}#page=${page?.ref.match(/\d+/)?.[0]||1}`}/>: /\.(png|jpe?g|webp|bmp)$/i.test(doc.name)?<img alt={doc.name} src={url(doc.id)} className="max-h-[480px] w-full object-contain"/>:null}{page?.rows&&<div className="max-h-80 overflow-auto"><table className="text-sm"><tbody>{page.rows.map((r,i)=><tr key={i}><th className="border p-2">{i+1}</th>{r.map((v,j)=><td key={j} className="border p-2">{v}</td>)}</tr>)}</tbody></table></div>}<details open={!/\.pdf$/i.test(doc.name)}><summary>Extracted source text · {page?.method||'Not read'}</summary><pre className="max-h-72 overflow-auto whitespace-pre-wrap text-sm">{page?.error||page?.text||'This source has not been read yet.'}</pre></details></div>
 <div className="min-w-0 space-y-3 rounded border p-3"><h4 className="font-semibold">Source-linked findings and summary</h4><p className="text-sm text-slate-500">Confidence is a review signal, not a guarantee. Confirm against the original before estimating.</p>{!doc.fields.length&&<p>No readable findings yet. Check the processing status and source text.</p>}{doc.fields.map(f=><div key={f.id} className={`rounded border p-3 ${f.confidence<80?'border-amber-400 bg-amber-50':''}`}><strong className="text-sm">{f.label}</strong><textarea aria-label={`${f.label} value`} className="mt-2 w-full rounded border bg-white p-2 text-sm" key={`${f.id}:${f.value}`} defaultValue={f.value} onBlur={e=>{if(e.target.value!==f.value)void review(f,'Needs review',e.target.value);}}/><p className="text-sm text-slate-600">{doc.name} · {f.source} · {f.origin} · {f.method} · {Math.round(f.confidence)}% · {f.status}</p><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setSource(doc.pages.find(p=>f.source.startsWith(p.ref))?.ref||f.source)}>View source</Button><Button size="sm" disabled={busy} onClick={()=>review(f,'Confirmed')}>Confirm</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>review(f,'Rejected')}>Reject</Button></div></div>)}</div></div>}
 {!!missing.length&&<div className="rounded border border-amber-200 bg-amber-50 p-3"><h4 className="font-semibold">Clarification checklist — not identified automatically</h4><p className="text-sm">{missing.join(' · ')}</p><p className="text-sm">Check the originals: absence from extraction does not establish absence from the tender.</p></div>}{!!pack.changes.length&&<section className="rounded border p-3"><h4 className="font-semibold">Addenda differences — estimate review required</h4>{pack.changes.map((c,i)=><div key={i} className="border-b py-3 text-sm"><strong>{c.label} · {c.source}</strong><p>Earlier: {c.before}</p><p>Addendum: {c.after}</p></div>)}</section>}
 </section>;
}
