import {withActor} from '@/lib/platform/route';
import { currentOrganisationId as ORG, cleanText, requireBindings } from "@/lib/dockets-db";
export const dynamic = "force-dynamic";
const jsonError = (message:string,status=400)=>Response.json({error:message},{status});
async function handlePOST(req:Request){
  try {
    const {db}=requireBindings(); const body=await req.json() as Record<string,unknown>; const action=String(body.action||"");
    // Old actions fabricated splits or reported OCR success without reading a
    // file. Keep records unchanged until actual regions/results are supplied.
    if(['split','merge'].includes(action)) return jsonError('Select distinct source regions before splitting or merging. Boundary editing is not yet available.',422);
    if(action.startsWith('reprocess')) return jsonError('Use Reprocess in the docket review screen to read the original and review the proposed values.',422);
    const ids=Array.isArray(body.ids)?body.ids.map(v=>cleanText(v,80)).filter(Boolean):[cleanText(body.id,80)].filter(Boolean); if(!ids.length)return jsonError("A docket ID is required.");
    const rows=[] as Array<Record<string,unknown>>; for(const id of ids){const row=await db.prepare("SELECT * FROM dockets WHERE organisation_id=? AND id=?").bind(ORG(),id).first<Record<string,unknown>>(); if(!row)return jsonError("Docket not found.",404); rows.push(row);}
    const now=new Date().toISOString();
    if(action==="split"){
      const sections=Array.isArray(body.sections)?body.sections as Array<Record<string,unknown>>:[]; if(sections.length<2)return jsonError("Provide at least two split sections."); const src=rows[0]; const created=[];
      for(const section of sections){const id=crypto.randomUUID(); const text=cleanText(section.rawText||src.raw_text,12000); await db.prepare(`INSERT INTO dockets (id,organisation_id,docket_no,work_date,client,project,crew,vehicle,start_time,finish_time,break_hours,labour_hours,quantity,quantity_unit,amount,po_number,notes,status,confidence,source_name,source_key,raw_text,source_page,source_crop,field_confidence,line_items,links,extraction_method,profile_id,created_at,updated_at) SELECT ?,organisation_id,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, ?,? FROM dockets WHERE id=? AND organisation_id=?`).bind(id,section.docketNo||"UNREAD",section.workDate||src.work_date,section.client||src.client,section.project||src.project,section.crew||src.crew,section.vehicle||src.vehicle,section.startTime||src.start_time,section.finishTime||src.finish_time,section.breakHours??src.break_hours,section.labourHours??src.labour_hours,section.quantity??src.quantity,section.quantityUnit||src.quantity_unit,section.amount??0,section.poNumber||src.po_number,`Split from ${src.docket_no}`,"review",section.confidence??src.confidence,src.source_name,src.source_key,text,section.sourcePage??src.source_page,section.sourceCrop||`split-section-${created.length+1}`,JSON.stringify(section.fieldConfidence||{}),JSON.stringify(section.lineItems||[]),JSON.stringify({...JSON.parse(String(src.links||"{}")),splitFrom:src.id}),"reprocessed",section.profileId||src.profile_id,now,now,src.id,ORG()).run(); created.push({id});}
      await db.prepare("INSERT INTO audit_events (id,organisation_id,name,status,metadata,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),ORG(),"docket.split","completed",JSON.stringify({sourceId:src.id,created}),now).run(); return Response.json({created});
    }
    if(action==="merge"){
      if(rows.length<2)return jsonError("Select at least two adjacent dockets."); const first=rows[0]; const id=crypto.randomUUID(); const text=rows.map(r=>String(r.raw_text||"")).filter(Boolean).join("\n\n--- merged source section ---\n\n"); const crops=rows.map(r=>String(r.source_crop||"full-page")).join(" + "); await db.prepare(`INSERT INTO dockets (id,organisation_id,docket_no,work_date,client,project,crew,vehicle,start_time,finish_time,break_hours,labour_hours,quantity,quantity_unit,amount,po_number,notes,status,confidence,source_name,source_key,raw_text,source_page,source_crop,field_confidence,line_items,links,extraction_method,profile_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,ORG(),`MERGED-${String(first.docket_no)}`,first.work_date,first.client,first.project,first.crew,first.vehicle,first.start_time,first.finish_time,Number(first.break_hours||0),rows.reduce((n,r)=>n+Number(r.labour_hours||0),0),rows.reduce((n,r)=>n+Number(r.quantity||0),0),first.quantity_unit,rows.reduce((n,r)=>n+Number(r.amount||0),0),first.po_number,"Merged source sections; originals retained.","review",Math.min(...rows.map(r=>Number(r.confidence||0))),rows.map(r=>String(r.source_name||"")).join("; "),rows.map(r=>String(r.source_key||"")).find(Boolean)||"",text,first.source_page,crops,"{}",JSON.stringify(rows.flatMap(r=>{try{return JSON.parse(String(r.line_items||"[]"))}catch{return []}})),JSON.stringify({mergedFrom:ids}),"merged",first.profile_id,now,now).run(); await db.prepare("INSERT INTO audit_events (id,organisation_id,name,status,metadata,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),ORG(),"docket.merge","completed",JSON.stringify({sourceIds:ids,createdId:id}),now).run(); return Response.json({created:{id},originals:ids});
    }
    if(action==="reprocess"||action==="reprocess-page"||action==="reprocess-profile"){
      const profileId=cleanText(body.profileId,120); const method=action==="reprocess-profile"?"profile-reprocess":"local-ocr-reprocess"; await db.prepare("UPDATE dockets SET status='review', extraction_method=?, profile_id=COALESCE(NULLIF(?,''),profile_id), notes=CASE WHEN notes='' THEN 'Reprocessed from original source.' ELSE CONCAT(notes,' Reprocessed from original source.') END, updated_at=? WHERE organisation_id=? AND id=?").bind(method,profileId,now,ORG(),ids[0]).run(); await db.prepare("INSERT INTO audit_events (id,organisation_id,name,status,metadata,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),ORG(),`docket.${action}`,"completed",JSON.stringify({docketId:ids[0],profileId:profileId||null}),now).run(); return Response.json({updated:true,id:ids[0],extractionMethod:method,status:"review"});
    }
    return jsonError("Unknown docket action.");
  } catch(e){console.error(e);return jsonError("Docket action failed.",503)}
}

export const POST=withActor(handlePOST,'write','dockets');
