import ExcelJS from 'exceljs';
import {Readable} from 'node:stream';
import {actorContext} from '@/lib/platform/context';
import {can} from '@/lib/platform/permissions';
import {audit} from '@/lib/platform/audit';
import {fail} from '@/lib/platform/http';
import {query} from '@/lib/platform/sql';
import {savePlant,saveWorker,WORKER_STATUSES,PLANT_STATUSES,EMPLOYMENT_TYPES} from './resources';

export type ResourceImportKind='workers'|'plant';
export type ImportPreviewRow={rowNumber:number;label:string;action:'create'|'update'|'skip'|'error';matchId:string|null;matchLabel:string|null;errors:string[];warnings:string[];values:Record<string,string|number|null>};
export type ImportPreview={kind:ResourceImportKind;fileName:string;mappedHeaders:Array<{source:string;target:string|null}>;availableFields:Array<{key:string;label:string}>;unmappedHeaders:string[];rows:ImportPreviewRow[];summary:{total:number;create:number;update:number;skip:number;error:number}};
type Def={key:string;label:string;aliases:string[];rate?:boolean};
const W:Def[]=[
 ['firstName','First name',['first name','firstname','given name','first']],['lastName','Last name',['last name','lastname','surname','family name']],['fullName','Full name',['name','full name','employee name','worker name']],['employeeNumber','Employee number',['employee number','employee no','employee id','payroll id','payroll number','staff number']],['email','Email',['email','email address','work email']],['phone','Phone',['phone','phone number','mobile','mobile number','contact number']],['roleTitle','Role / trade',['role','role title','position','job title','trade','classification']],['employmentType','Employment type',['employment type','employment','engagement type','worker type']],['location','Base / location',['location','base','depot','branch','region']],['status','Status',['status','worker status','employee status']],['hourlyRate','Hourly rate',['hourly rate','hour rate','rate per hour','cost rate','labour rate','labor rate'],true]
].map(x=>({key:x[0] as string,label:x[1] as string,aliases:x[2] as string[],rate:Boolean(x[3])}));
const P:Def[]=[
 ['name','Plant / equipment name',['name','plant name','equipment name','asset name']],['plantNumber','Plant number',['plant number','plant no','asset number','asset id','unit number']],['registration','Registration',['registration','rego','registration number','rego number']],['category','Category',['category','type','plant type','equipment type','asset type']],['description','Description',['description','details','asset description']],['make','Make',['make','manufacturer','brand']],['model','Model',['model','model number']],['ownership','Ownership',['ownership','ownership type']],['complianceExpiry','Registration / compliance expiry',['compliance expiry','rego expiry','registration expiry','expiry date']],['location','Base / location',['location','base','depot','branch','region']],['status','Status',['status','plant status','equipment status','asset status']],['hourlyRate','Hourly rate',['hourly rate','hour rate','rate per hour'],true],['dayRate','Day rate',['day rate','daily rate','rate per day'],true]
].map(x=>({key:x[0] as string,label:x[1] as string,aliases:x[2] as string[],rate:Boolean(x[3])}));
const defs=(k:ResourceImportKind)=>k==='workers'?W:P;
const actor=()=>actorContext.getStore()!;
const h=(s:string)=>s.toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim();
const txt=(v:ExcelJS.CellValue)=>{if(v==null)return '';if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v).trim();if('text' in v)return String(v.text||'').trim();if('result' in v&&v.result!=null)return String(v.result).trim();if('richText' in v)return v.richText.map(x=>x.text).join('').trim();return ''};
const split=(s:string)=>{const a=s.trim().split(/\s+/).filter(Boolean);return {firstName:a.length>1?a.slice(0,-1).join(' '):(a[0]||''),lastName:a.length>1?(a.at(-1)||''):''}};
const date=(s:string)=>{if(!s)return {v:null,e:''};let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/),y=0,mo=0,d=0;if(m){y=+m[1];mo=+m[2];d=+m[3]}else{m=s.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);if(!m)return {v:null,e:'Use DD/MM/YYYY or YYYY-MM-DD.'};d=+m[1];mo=+m[2];y=+m[3]}const x=new Date(Date.UTC(y,mo-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===mo-1&&x.getUTCDate()===d?{v:[y,String(mo).padStart(2,'0'),String(d).padStart(2,'0')].join('-'),e:''}:{v:null,e:'Invalid date.'}};
const num=(s:string)=>{if(!s)return {v:null,e:''};const n=Number(s.replace(/[$,\s]/g,''));return Number.isFinite(n)&&n>=0?{v:n,e:''}:{v:null,e:'Must be a positive number.'}};
const workerStatus=(s:string)=>({active:'Active',current:'Active',employed:'Active',leave:'Leave','on leave':'Leave',inactive:'Inactive',terminated:'Inactive',former:'Inactive',left:'Inactive'} as Record<string,string>)[h(s)]||null;
const employment=(s:string)=>({employee:'employee','full time':'employee','part time':'employee',permanent:'employee',casual:'casual',contractor:'contractor',subcontractor:'contractor','labour hire':'labour hire','labor hire':'labour hire'} as Record<string,string>)[h(s)]||null;
const plantStatus=(s:string)=>({available:'Available',active:'Available',allocated:'Allocated','in use':'Allocated',maintenance:'Maintenance',repair:'Maintenance','out of service':'Out of service',defect:'Out of service',unavailable:'Unavailable',inactive:'Inactive',retired:'Inactive'} as Record<string,string>)[h(s)]||null;
const own=(s:string)=>({owned:'owned',own:'owned',hired:'hired',hire:'hired',rented:'hired',leased:'leased',lease:'leased'} as Record<string,string>)[h(s)]||null;
async function sheet(file:File){if(file.size>8*1024*1024)fail(413,'Use a spreadsheet smaller than 8 MB.');const n=file.name.toLowerCase();if(!n.endsWith('.xlsx')&&!n.endsWith('.csv'))fail(400,'Use .xlsx or .csv. Save older .xls files as .xlsx first.');const bytes=Buffer.from(await file.arrayBuffer()),w=new ExcelJS.Workbook();if(n.endsWith('.csv'))return w.csv.read(Readable.from([bytes]));await w.xlsx.read(Readable.from([bytes]));const s=w.worksheets.find(x=>x.state==='visible')||w.worksheets[0];if(!s)fail(400,'Spreadsheet has no worksheet.');return s}
async function parse(file:File,kind:ResourceImportKind,manual:Record<string,string>={}){const s=await sheet(file),map=new Map<string,string>(),valid=new Set(defs(kind).map(d=>d.key));for(const d of defs(kind)){map.set(h(d.label),d.key);for(const a of d.aliases)map.set(h(a),d.key)}const heads:Array<{source:string;key:string|null}>=[];s.getRow(1).eachCell({includeEmpty:false},c=>{const source=txt(c.value),chosen=manual[source];heads[Number(c.col)-1]={source,key:chosen&&valid.has(chosen)?chosen:(map.get(h(source))||null)}});const meaningful=heads.filter(Boolean);if(!meaningful.length)fail(400,'Row 1 must contain headings.');const mapped=meaningful.filter(x=>x.key);for(const key of new Set(mapped.map(x=>x.key))){if(key&&mapped.filter(x=>x.key===key).length>1)fail(400,'More than one spreadsheet column maps to '+(defs(kind).find(d=>d.key===key)?.label||key)+'. Choose only one source column for each field.');}const rows:Array<{rowNumber:number;cells:Record<string,string>;provided:Set<string>}>=[];for(let r=2;r<=Math.min(s.rowCount,2001);r++){const cells:Record<string,string>={},provided=new Set<string>();let any=false;for(let i=0;i<heads.length;i++){const hd=heads[i];if(!hd?.key)continue;const v=txt(s.getRow(r).getCell(i+1).value);if(v!==''){cells[hd.key]=v;provided.add(hd.key);any=true}}if(any)rows.push({rowNumber:r,cells,provided})}if(s.rowCount>2001)fail(400,'Maximum 2,000 data rows per import.');return {rows,heads}}
function workerValues(r:{cells:Record<string,string>;provided:Set<string>},e:Record<string,unknown>|null,allowRates:boolean):{errors:string[];warnings:string[];values:Record<string,string|number|null>}{const c=r.cells,p=r.provided,errors:string[]=[],warnings:string[]=[];let fn=c.firstName||'',ln=c.lastName||'';if(!fn&&c.fullName)({firstName:fn,lastName:ln}=split(c.fullName));if(!fn)errors.push('First name is required.');if(c.email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(c.email))errors.push('Invalid email.');const st=c.status?workerStatus(c.status):null;if(c.status&&!st)errors.push('Status must be Active, Leave or Inactive.');const et=c.employmentType?employment(c.employmentType):null;if(c.employmentType&&!et)errors.push('Employment type must be employee, casual, contractor or labour hire.');const rate=num(c.hourlyRate||'');if(rate.e)errors.push('Hourly rate '+rate.e);if(c.hourlyRate&&!allowRates)warnings.push('Hourly rate ignored for this role.');const en=split(String(e?.name||''));return {errors,warnings,values:{firstName:p.has('firstName')||p.has('fullName')?fn:String(e?.first_name||en.firstName||''),lastName:p.has('lastName')||p.has('fullName')?ln:String(e?.last_name||en.lastName||''),employeeNumber:p.has('employeeNumber')?c.employeeNumber||null:(e?.employee_number as string|null)||null,email:p.has('email')?c.email||null:(e?.email as string|null)||null,phone:p.has('phone')?c.phone||null:(e?.phone as string|null)||null,roleTitle:p.has('roleTitle')?c.roleTitle||null:(e?.role_title as string|null)||null,employmentType:p.has('employmentType')?et:(e?.employment_type as string|null)||null,userId:(e?.user_id as string|null)||null,hourlyRate:allowRates?(p.has('hourlyRate')?rate.v:(e?.hourly_rate==null?null:Number(e.hourly_rate))):null,location:p.has('location')?c.location||null:(e?.location as string|null)||null,status:p.has('status')?(st||'Active'):String(e?.status||'Active')}}}
function plantValues(r:{cells:Record<string,string>;provided:Set<string>},e:Record<string,unknown>|null,allowRates:boolean):{errors:string[];warnings:string[];values:Record<string,string|number|null>}{const c=r.cells,p=r.provided,errors:string[]=[],warnings:string[]=[];const st=c.status?plantStatus(c.status):null;if(c.status&&!st)errors.push('Unrecognised plant status.');const ow=c.ownership?own(c.ownership):null;if(c.ownership&&!ow)errors.push('Ownership must be owned, hired or leased.');const ex=date(c.complianceExpiry||'');if(ex.e)errors.push(ex.e);const hr=num(c.hourlyRate||''),dr=num(c.dayRate||'');if(hr.e)errors.push('Hourly rate '+hr.e);if(dr.e)errors.push('Day rate '+dr.e);if((c.hourlyRate||c.dayRate)&&!allowRates)warnings.push('Rate columns ignored for this role.');const name=p.has('name')?c.name:String(e?.name||'');if(!name)errors.push('Plant / equipment name is required.');return {errors,warnings,values:{name,plantNumber:p.has('plantNumber')?c.plantNumber||null:(e?.plant_number as string|null)||null,registration:p.has('registration')?c.registration||null:(e?.registration as string|null)||null,category:p.has('category')?c.category||null:(e?.category as string|null)||null,description:p.has('description')?c.description||null:(e?.description as string|null)||null,make:p.has('make')?c.make||null:(e?.make as string|null)||null,model:p.has('model')?c.model||null:(e?.model as string|null)||null,ownership:p.has('ownership')?ow:(e?.ownership as string|null)||null,hourlyRate:allowRates?(p.has('hourlyRate')?hr.v:(e?.hourly_rate==null?null:Number(e.hourly_rate))):null,dayRate:allowRates?(p.has('dayRate')?dr.v:(e?.day_rate==null?null:Number(e.day_rate))):null,complianceExpiry:p.has('complianceExpiry')?ex.v:(e?.compliance_expiry as string|null)||null,location:p.has('location')?c.location||null:(e?.location as string|null)||null,status:p.has('status')?(st||'Available'):String(e?.status||'Available')}}}
function addMatch(map:Map<string,Record<string,unknown>[]>,key:unknown,row:Record<string,unknown>){const k=String(key||'').trim().toLowerCase();if(!k)return;map.set(k,[...(map.get(k)||[]),row]);}
function resolveMatch(kind:ResourceImportKind,c:Record<string,string>,byA:Map<string,Record<string,unknown>[]>,byB:Map<string,Record<string,unknown>[]>,byName:Map<string,Record<string,unknown>[]>,errors:string[]){
 const k1=kind==='workers'?c.employeeNumber:c.plantNumber,k2=kind==='workers'?c.email:c.registration,name=kind==='workers'?(c.fullName||[c.firstName,c.lastName].filter(Boolean).join(' ')):c.name;
 const candidates:Record<string,unknown>[]=[];
 if(k1)candidates.push(...(byA.get(k1.trim().toLowerCase())||[]));
 if(k2)candidates.push(...(byB.get(k2.trim().toLowerCase())||[]));
 if(!candidates.length&&name)candidates.push(...(byName.get(name.trim().toLowerCase())||[]));
 const unique=[...new Map(candidates.map(x=>[String(x.id),x])).values()];
 if(unique.length>1){errors.push('More than one existing record matches this row. Add a unique '+(kind==='workers'?'employee number or email.':'plant number or registration.'));return null;}
 return unique[0]||null;
}
export async function previewResourceSpreadsheet(file:File,kind:ResourceImportKind,updateExisting=true,manual:Record<string,string>={}):Promise<ImportPreview>{const a=actor(),allowRates=can(a.role,'commercial.view'),x=await parse(file,kind,manual),existing=kind==='workers'?await query("SELECT id,name,status,employee_number,first_name,last_name,email,phone,role_title,employment_type,user_id,hourly_rate,location,revision FROM workers WHERE organisation_id=? AND LOWER(status)<>'archived'",[a.organisationId]):await query("SELECT id,name,status,plant_number,registration,category,description,make,model,ownership,hourly_rate,day_rate,compliance_expiry,location,revision FROM plant WHERE organisation_id=? AND LOWER(status)<>'archived'",[a.organisationId]);const byA=new Map<string,Record<string,unknown>[]>(),byB=new Map<string,Record<string,unknown>[]>(),byName=new Map<string,Record<string,unknown>[]>();for(const e of existing){if(kind==='workers'){addMatch(byA,e.employee_number,e);addMatch(byB,e.email,e)}else{addMatch(byA,e.plant_number,e);addMatch(byB,e.registration,e)}addMatch(byName,e.name,e)}const seen=new Set<string>(),rows:ImportPreviewRow[]=[];for(const r of x.rows){const c=r.cells,k1=kind==='workers'?c.employeeNumber:c.plantNumber,k2=kind==='workers'?c.email:c.registration,name=kind==='workers'?(c.fullName||[c.firstName,c.lastName].filter(Boolean).join(' ')):c.name,matchErrors:string[]=[],e=resolveMatch(kind,c,byA,byB,byName,matchErrors),v=kind==='workers'?workerValues(r,e,allowRates):plantValues(r,e,allowRates),keys=[k1?'a:'+k1.trim().toLowerCase():'',k2?'b:'+k2.trim().toLowerCase():'',!k1&&!k2&&name?'n:'+name.trim().toLowerCase():''].filter(Boolean);v.errors.unshift(...matchErrors);if(keys.some(key=>seen.has(key)))v.errors.push('Duplicate row in spreadsheet.');for(const key of keys)seen.add(key);const action:'create'|'update'|'skip'|'error'=v.errors.length?'error':e?(updateExisting?'update':'skip'):'create';rows.push({rowNumber:r.rowNumber,label:kind==='workers'?[v.values.firstName,v.values.lastName].filter(Boolean).join(' '):String(v.values.name||''),action,matchId:e?String(e.id):null,matchLabel:e?String(e.name):null,errors:v.errors,warnings:v.warnings,values:v.values})}return {kind,fileName:file.name,mappedHeaders:x.heads.filter(Boolean).map(z=>({source:z.source,target:z.key})),availableFields:defs(kind).filter(d=>!d.rate||allowRates).map(d=>({key:d.key,label:d.label})),unmappedHeaders:x.heads.filter(z=>z&&!z.key).map(z=>z.source),rows,summary:{total:rows.length,create:rows.filter(r=>r.action==='create').length,update:rows.filter(r=>r.action==='update').length,skip:rows.filter(r=>r.action==='skip').length,error:rows.filter(r=>r.action==='error').length}}}
export async function applyResourceSpreadsheet(file:File,kind:ResourceImportKind,updateExisting=true,manual:Record<string,string>={}){const a=actor(),p=await previewResourceSpreadsheet(file,kind,updateExisting,manual);let created=0,updated=0,skipped=0,failed=0;const results=[] as Array<{rowNumber:number;label:string;status:string;error?:string}>;for(const r of p.rows){if(r.action==='error'||r.action==='skip'){skipped++;results.push({rowNumber:r.rowNumber,label:r.label,status:'skipped',error:r.errors.join(' ')||undefined});continue}try{if(kind==='workers'){const v=r.values,rev=r.matchId?(await query("SELECT revision FROM workers WHERE organisation_id=? AND id=?",[a.organisationId,r.matchId]))[0]?.revision:null;await saveWorker(r.matchId,r.matchId?Number(rev):null,{firstName:String(v.firstName||''),lastName:String(v.lastName||''),employeeNumber:v.employeeNumber??'',email:v.email??'',phone:v.phone??'',roleTitle:v.roleTitle??'',employmentType:v.employmentType??'',userId:v.userId??'',hourlyRate:v.hourlyRate??'',location:v.location??'',status:String(v.status||'Active')})}else{const v=r.values,rev=r.matchId?(await query("SELECT revision FROM plant WHERE organisation_id=? AND id=?",[a.organisationId,r.matchId]))[0]?.revision:null;await savePlant(r.matchId,r.matchId?Number(rev):null,{name:String(v.name||''),plantNumber:v.plantNumber??'',registration:v.registration??'',category:v.category??'',description:v.description??'',make:v.make??'',model:v.model??'',ownership:v.ownership??'',hourlyRate:v.hourlyRate??'',dayRate:v.dayRate??'',complianceExpiry:v.complianceExpiry??'',location:v.location??'',status:String(v.status||'Available')})}if(r.action==='create')created++;else updated++;results.push({rowNumber:r.rowNumber,label:r.label,status:r.action})}catch(e){failed++;results.push({rowNumber:r.rowNumber,label:r.label,status:'failed',error:e instanceof Error?e.message:'Import failed.'})}}await audit({event:'resource_import.completed',entityType:kind==='workers'?'worker':'plant',entityId:a.organisationId,summary:'Spreadsheet import: '+kind+' — '+created+' created, '+updated+' updated, '+skipped+' skipped, '+failed+' failed',after:{fileName:file.name,created,updated,skipped,failed,total:p.summary.total}});return {summary:{total:p.summary.total,created,updated,skipped,failed},results}}
export async function resourceTemplate(kind:ResourceImportKind){const includeRates=can(actor().role,'commercial.view'),d=defs(kind).filter(x=>(kind!=='workers'||x.key!=='fullName')&&(!x.rate||includeRates)),w=new ExcelJS.Workbook(),info=w.addWorksheet('Instructions'),s=w.addWorksheet('Data');info.columns=[{width:24},{width:80}];info.addRows([[kind==='workers'?'Employee bulk import':'Fleet & plant bulk import',''],['How it works','Fill the Data sheet, upload it in Infrastruct, preview matches, then import.'],['Safe re-runs',kind==='workers'?'Matches use Employee number, then Email, then exact Name.':'Matches use Plant number, then Registration, then exact Name.'],['Blank cells','Blank cells do not overwrite existing values when updating.'],['Dates','Use DD/MM/YYYY or YYYY-MM-DD.'],['Existing files','You can upload your own .xlsx/.csv. Common headings like Payroll ID, Mobile, Trade, Depot and Rego are recognised automatically.']]);info.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFD85618'}}});s.addRow(d.map(x=>x.label));const sample=kind==='workers'?['Jordan','Taylor','EMP-001','jordan@example.com','0400 000 000','Supervisor','employee','Sydney','Active','58.50']:['Excavator 05','PL-005','ABC12D','Excavator','5 tonne excavator','Kubota','U55-4','owned','31/12/2027','Sydney','Available','95','760'];s.addRow(sample.slice(0,d.length));s.views=[{state:'frozen',ySplit:1}];s.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF17212B'}}});s.columns.forEach((c,i)=>c.width=Math.min(28,Math.max(15,(d[i]?.label.length||10)+4)));const si=d.findIndex(x=>x.key==='status')+1;if(si)for(let r=2;r<1002;r++)s.getCell(r,si).dataValidation={type:'list',allowBlank:true,formulae:['"'+(kind==='workers'?WORKER_STATUSES:PLANT_STATUSES).join(',')+'"']};if(kind==='workers'){const i=d.findIndex(x=>x.key==='employmentType')+1;if(i)for(let r=2;r<1002;r++)s.getCell(r,i).dataValidation={type:'list',allowBlank:true,formulae:['"'+EMPLOYMENT_TYPES.join(',')+'"']}}if(kind==='plant'){const i=d.findIndex(x=>x.key==='ownership')+1;if(i)for(let r=2;r<1002;r++)s.getCell(r,i).dataValidation={type:'list',allowBlank:true,formulae:['"owned,hired,leased"']}}return Buffer.from(await w.xlsx.writeBuffer())}
