import {parseCsv,type TenderPage} from './tender';
import {loadPdfReader,loadTesseract} from '@/lib/document-readers';
export async function readTender(file:File,onPage:(page:TenderPage,total:number)=>Promise<void>,progress:(message:string)=>void){
 const ext=file.name.split('.').pop()?.toLowerCase();
 let worker:Awaited<ReturnType<NonNullable<Window['Tesseract']>['createWorker']>>|undefined;
 async function ocr(image:File|HTMLCanvasElement){await loadTesseract();if(!window.Tesseract)throw new Error('Local OCR could not load');worker ||= await window.Tesseract.createWorker('eng',1,{logger:m=>progress(`${m.status} ${Math.round(m.progress*100)}%`)});return (await worker.recognize(image,{rotateAuto:true})).data;}
 try{
 if(ext==='pdf'){await loadPdfReader();if(!window.pdfjsLib)throw new Error('PDF reader unavailable');const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;
 for(let i=1;i<=pdf.numPages;i++){let method:TenderPage['method']='pdf-text';try{progress(`Reading page ${i} of ${pdf.numPages}`);const p=await pdf.getPage(i),content=await p.getTextContent();let lastY:number|undefined;let text='';for(const item of content.items){const y=item.transform?.[5];text+=(lastY!==undefined&&y!==lastY?'\n':' ')+(item.str||'');lastY=y;}let confidence=99;if(text.replace(/\s/g,'').length<30){method='local-ocr';const base=p.getViewport({scale:2});const viewport=p.getViewport({scale:2*Math.min(1,3000/Math.max(base.width,base.height))});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const context=canvas.getContext('2d');if(!context)throw new Error('Page renderer unavailable');await p.render({canvasContext:context,viewport}).promise;const result=await ocr(canvas);text=result.text;confidence=result.confidence;canvas.width=canvas.height=0;}await onPage({ref:`Page ${i}`,text,confidence,method,...(!text.trim()?{error:'No readable text found; inspect drawing or scan manually'}:{})},pdf.numPages);}catch(e){await onPage({ref:`Page ${i}`,text:'',method,confidence:0,error:e instanceof Error?e.message:'Page failed'},pdf.numPages);}}
 }else if(['png','jpg','jpeg','webp','tif','tiff','bmp'].includes(ext||'')){const r=await ocr(file);await onPage({ref:'Page 1',text:r.text,confidence:r.confidence,method:'local-ocr',...(!r.text.trim()?{error:'No readable text found'}:{})},1);
 }else if(ext==='docx'){const mammoth=await import('mammoth');const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});const sections=r.value.split(/\n\s*\n/).filter(t=>t.trim());if(!sections.length)throw new Error('No DOCX text found; embedded images require separate OCR');for(let i=0;i<sections.length;i++)await onPage({ref:`Section ${i+1} (DOCX pagination unavailable)`,text:sections[i],method:'docx',confidence:98},sections.length);
 }else if(ext==='xlsx'){const ExcelJS=await import('exceljs');const book=new ExcelJS.Workbook();await book.xlsx.load(await file.arrayBuffer());for(const sheet of book.worksheets){const rows:string[][]=[];sheet.eachRow({includeEmpty:true},r=>{const row:string[]=[];for(let i=1;i<=sheet.columnCount;i++){const cell=r.getCell(i);row.push(cell.text);}rows.push(row);});await onPage({ref:`Sheet ${sheet.name}`,text:rows.map(r=>r.join(' | ')).join('\n'),rows,confidence:99,method:'xlsx'},book.worksheets.length);}
 }else if(ext==='csv'){const rows=parseCsv(await file.text());await onPage({ref:'Sheet CSV',text:rows.map(r=>r.join(' | ')).join('\n'),rows,method:'csv',confidence:99},1);
 }else throw new Error('Unsupported file type. Upload PDF, image, DOCX, XLSX or CSV. Original retained.');
 }finally{await worker?.terminate();}
}
