export type TenderPage={ref:string;text:string;method:'pdf-text'|'local-ocr'|'docx'|'xlsx'|'csv';confidence:number;rows?:string[][];error?:string};
export type TenderField={id:string;label:string;value:string;source:string;method:string;confidence:number;status:'Needs review'|'Confirmed'|'Rejected';origin:'Extracted'|'Inferred'|'Calculated'|'User corrected';original?:string};
export type TenderDoc={id:string;name:string;key?:string;type:string;size:number;uploadDate:string;addendumNumber:string;pageCount:number|null;processingStatus:string;ocrStatus:string;aiStatus:string;errors:string[];pages:TenderPage[];fields:TenderField[];revision:number;opportunityId:string;kind:string};
const categories:[string,RegExp][]=[
 ['Client',/\b(client|principal)\s*[:–-]/i],['Builder or principal',/\b(builder|head contractor|principal contractor)\s*[:–-]/i],['Project name',/\b(project|project name)\s*[:–-]/i],['Tender number',/\b(tender|contract)\s*(number|no\.?|reference|ref\.?)\s*[:–-]/i],['Site and location',/\b(site|location|address)\s*[:–-]/i],['Closing date',/\b(closing|closes|tender close|close date|deadline)\b/i],['Start date',/\b(start date|commencement|proposed start)\b/i],['Completion date',/\b(completion|complete by|finish date)\b/i],['Scope',/\b(scope|supply and lay|supply & lay|works comprise)\b/i],['Work types',/\b(asphalt|profiling|milling|spray seal|stabilisation|pothole|crack seal|sweeping|line marking|civil works)\b/i],['Areas',/\b(area|\d[\d,.]*\s*m[²2])\b|m²/i],['Lengths',/\blength\b/i],['Widths',/\bwidth\b/i],['Depths',/\b(depth|thickness|\d+\s*mm)\b/i],['Tonnes',/\b(tonnes|tonnage|\d[\d,.]*\s*t)\b/i],['Asphalt mixes',/\b(AC\s*(10|14|20)|SMA\s*\d*)\b/i],['Waste percentage',/\bwaste|allowance\s*%\b/i],['Profiling quantities',/\b(profiling|milling)\b/i],['Cartage requirements',/\b(cartage|haulage|truck|payload)\b/i],['Traffic-control requirements',/\b(traffic|TGS|TMP|VMP|PTCD|VMS|TMA|AWV|detour)\b/i],['Plant requirements',/\b(plant|paver|roller|excavator|profiler)\b/i],['Labour requirements',/\b(labour|crew|workers|operators)\b/i],['Accommodation and travel',/\b(accommodation|travel|LAFHA|lodging)\b/i],['Testing and QA requirements',/\b(testing|compaction|density|ITP|hold point|quality|QA)\b/i],['Contract conditions',/\b(payment|retention|liquidated|damages|security|bond|insurance|warranty|set.off|back.charge|GST|variation|extension of time|defects liability)\b/i],['Risks',/\b(risk|hazard|restricted|underground|services|night|weekend|environment|public|weather|access constraint)\b/i],['Exclusions',/\b(exclud|exclusion|not included|by others)\w*/i],['Clarifications required',/\b(TBC|TBD|clarif|not provided|to be confirmed|unclear)\w*/i],['Addenda changes',/\b(addendum|amend|revis|supersed|replac|changed)\w*/i]];
export const tenderLabels=categories.map(([label])=>label);
export function extractTender(pages:TenderPage[]):TenderField[]{const fields:TenderField[]=[];for(const page of pages){if(page.error)continue;for(const line of page.text.split(/\n+/).map(s=>s.trim()).filter(Boolean)){for(const [label,re] of categories){if(re.test(line))fields.push({id:`${page.ref}:${fields.length}`,label,value:line,source:page.ref,method:page.method,confidence:Math.min(page.confidence,label==='Risks'?65:85),status:'Needs review',origin:'Extracted'});}}if(page.rows?.length){const header=page.rows.findIndex(r=>r.some(v=>/description|item|work/i.test(v))&&r.some(v=>/qty|quantity/i.test(v)));if(header>=0){const headers=page.rows[header];for(let i=header+1;i<page.rows.length;i++){const row=page.rows[i];if(row.some(v=>v.trim()))fields.push({id:`${page.ref}:boq:${i}`,label:'BOQ item',value:headers.map((h,j)=>`${h}: ${row[j]||''}`).join(' | '),source:`${page.ref}, row ${i+1}`,method:page.method,confidence:90,status:'Needs review',origin:'Extracted'});}}}}
return fields;}
export function tenderDifferences(docs:TenderDoc[]){const changes:{label:string;before:string;after:string;source:string}[]=[];for(let i=0;i<docs.length;i++){if(!docs[i].addendumNumber)continue;for(const field of docs[i].fields||[]){const prior=docs.slice(0,i).flatMap(d=>d.fields||[]).filter(f=>f.label===field.label&&f.status!=='Rejected');if(prior.length&&!prior.some(f=>f.value===field.value))changes.push({label:field.label,before:prior.map(f=>f.value).join('; '),after:field.value,source:`${docs[i].name} · ${field.source}`});}}return changes;}
export function parseCsv(text:string):string[][]{const out:string[][]=[];let row:string[]=[],cell='',quoted=false;const delimiter=(text.split('\n')[0].match(/;/g)||[]).length>(text.split('\n')[0].match(/,/g)||[]).length?';':',';for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===delimiter&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))out.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(Boolean))out.push(row);if(quoted)throw new Error('Unclosed quoted CSV cell');return out;}
