// Isomorphic SWMS structure and the standard high-risk construction work
// library used to generate editable drafts. Suggestions only — a competent
// person must review site-specific hazards and controls before approval.
export type SwmsStep={step:string;hazards:string;controls:string;responsible:string;residualRisk:string};
export type SwmsContent={activity:string;location:string;highRiskWork:string[];workSteps:SwmsStep[];plant:string;equipment:string;substances:string;ppe:string[];competencies:string;licences:string;permits:string;emergency:string;responsiblePeople:string;review:string};
export type SwmsQuestionnaire={activity:string;location?:string;workSteps?:string[];highRiskWork?:string[];plant?:string;equipment?:string;substances?:string;ppe?:string[];competencies?:string;licences?:string;permits?:string;emergency?:string;responsiblePeople?:string};

export const PPE_OPTIONS=['Hard hat','Hi-vis clothing','Safety boots','Safety glasses','Hearing protection','Gloves','Respirator','Sun protection','Harness','Face shield'] as const;
export const HIGH_RISK_WORK=[
 {key:'traffic',label:'Work in or adjacent to a road or traffic corridor',hazards:'Struck by passing traffic; reversing vehicles; poor visibility.',controls:'Approved traffic guidance scheme implemented by accredited traffic controllers; exclusion zones; hi-vis PPE; spotter for reversing plant.',ppe:['Hi-vis clothing'],competency:'Traffic control accreditation for controllers',permit:'Road occupancy licence / traffic management plan'},
 {key:'mobile-plant',label:'Work near powered mobile plant',hazards:'Struck by or crushed by mobile plant; plant rollover.',controls:'Plant/people exclusion zones; licensed operators; pre-start checks; reversing alarms and cameras; spotter where visibility is limited.',ppe:['Hi-vis clothing'],competency:'Plant operator competency / VOC',permit:''},
 {key:'excavation',label:'Excavation deeper than 1.5 m or trenching',hazards:'Trench collapse; falls into excavation; contact with buried services.',controls:'Dial-before-you-dig and service location; benching, battering or shoring; edge protection; safe access/egress.',ppe:['Hard hat'],competency:'Excavation supervisor competency',permit:'Excavation / ground disturbance permit'},
 {key:'services',label:'Work near underground or overhead services',hazards:'Electrocution; gas strike; service damage.',controls:'Services located and marked; potholing; safe approach distances; spotter for overhead lines.',ppe:[],competency:'Service locator qualification',permit:'Permit to work near services'},
 {key:'height',label:'Work at height (risk of fall over 2 m)',hazards:'Falls from height; falling objects.',controls:'Edge protection or scaffolding; harness and anchor where required; tool tethering; exclusion zone below.',ppe:['Harness','Hard hat'],competency:'Working at heights',permit:''},
 {key:'confined-space',label:'Confined space entry',hazards:'Oxygen deficiency; toxic atmosphere; engulfment.',controls:'Confined space permit; atmospheric testing; standby person; rescue plan.',ppe:['Respirator'],competency:'Confined space entry',permit:'Confined space entry permit'},
 {key:'hot-works',label:'Hot works / hot bitumen or asphalt',hazards:'Burns; fire; fumes.',controls:'Hot works permit; fire extinguisher on site; temperature-rated PPE; fume management.',ppe:['Gloves','Face shield'],competency:'',permit:'Hot works permit'},
 {key:'substances',label:'Hazardous chemicals or substances',hazards:'Inhalation, skin contact, spills.',controls:'Current SDS on site; correct storage and labelling; spill kit; PPE per SDS.',ppe:['Gloves','Safety glasses'],competency:'',permit:''},
 {key:'silica',label:'Cutting, grinding or profiling generating dust (silica)',hazards:'Respirable crystalline silica exposure; noise.',controls:'Water suppression or on-tool extraction; respiratory protection; air monitoring.',ppe:['Respirator','Hearing protection'],competency:'',permit:''},
 {key:'lifting',label:'Lifting operations / cranes',hazards:'Dropped loads; plant overturn.',controls:'Lift plan; licensed crane operator and dogger; exclusion zone; certified lifting gear.',ppe:['Hard hat'],competency:'High risk work licence (crane / dogging)',permit:'Lift plan approval'},
] as const;
