import {mysqlTable,varchar,text,boolean,timestamp,index} from 'drizzle-orm/mysql-core';
const id=()=>varchar('id',{length:191}).primaryKey();
const dates=()=>({createdAt:timestamp('created_at',{fsp:3}).notNull(),updatedAt:timestamp('updated_at',{fsp:3}).notNull()});
// Identity/session tables are global; business membership is in users, never client claims.
export const user=mysqlTable('auth_user',{id:id(),name:text('name').notNull(),email:varchar('email',{length:254}).notNull().unique(),emailVerified:boolean('email_verified').notNull().default(false),image:text('image'),...dates()});
export const session=mysqlTable('auth_session',{id:id(),expiresAt:timestamp('expires_at',{fsp:3}).notNull(),token:varchar('token',{length:255}).notNull().unique(),...dates(),ipAddress:text('ip_address'),userAgent:text('user_agent'),userId:varchar('user_id',{length:191}).notNull().references(()=>user.id,{onDelete:'cascade'})},t=>[index('auth_session_user').on(t.userId)]);
export const account=mysqlTable('auth_account',{id:id(),accountId:varchar('account_id',{length:191}).notNull(),providerId:varchar('provider_id',{length:191}).notNull(),userId:varchar('user_id',{length:191}).notNull().references(()=>user.id,{onDelete:'cascade'}),accessToken:text('access_token'),refreshToken:text('refresh_token'),idToken:text('id_token'),accessTokenExpiresAt:timestamp('access_token_expires_at',{fsp:3}),refreshTokenExpiresAt:timestamp('refresh_token_expires_at',{fsp:3}),scope:text('scope'),password:text('password'),...dates()},t=>[index('auth_account_user').on(t.userId)]);
export const verification=mysqlTable('auth_verification',{id:id(),identifier:varchar('identifier',{length:255}).notNull(),value:text('value').notNull(),expiresAt:timestamp('expires_at',{fsp:3}).notNull(),...dates()},t=>[index('auth_verification_identifier').on(t.identifier)]);
export const invitations=mysqlTable('organisation_invitations',{id:id(),organisationId:varchar('organisation_id',{length:191}).notNull(),email:varchar('email',{length:254}).notNull(),role:varchar('role',{length:20}).notNull(),tokenHash:varchar('token_hash',{length:64}).notNull().unique(),invitedBy:varchar('invited_by',{length:191}).notNull(),expiresAt:timestamp('expires_at',{fsp:3}).notNull(),acceptedAt:timestamp('accepted_at',{fsp:3}),createdAt:timestamp('created_at',{fsp:3}).notNull()},t=>[index('invitations_org').on(t.organisationId)]);
